/**
 * "Why this number" panels (trust-and-transparency-layer, steps 2–3):
 * expandable explainers that trace the two probabilistic headline outputs —
 * the Monte Carlo success % and the optimizer recommendation — to their
 * method, inputs, and the evidence already computed for them. Pure rendering
 * over existing payloads; no engine work happens here.
 */

import { Link } from 'react-router'

import type { MonteCarloSummary } from '@retiregolden/engine/montecarlo/run'
import type { ExactLedgerTournamentSummary } from '@retiregolden/engine/projection/optimizePlan'
import { ACA_VETO_ROW_NOTE, acaVetoExplanation } from './acaVetoCopy'
import { fmtMoney, fmtMoneyCompact } from './format'
import {
  RETIREMENT_ACTION_READINESS_VETO_ROW_NOTE,
  retirementActionReadinessVetoExplanation,
} from './retirementActionReadinessVetoCopy'

function fmtSignedMoney(v: number): string {
  return `${v >= 0 ? '+' : '−'}${fmtMoney(Math.abs(v))}`
}

/**
 * Decomposes the success gauge: what counts as success, how the markets were
 * generated (model, paths, seed, precision), which ledger years the failing
 * paths actually deplete in, and how wide the first decade's outcomes spread
 * (sequence-of-returns sensitivity). Everything renders from the existing
 * `MonteCarloSummary`.
 */
export function WhySuccessPanel({
  summary,
  modelLabel,
  seed,
  planId,
}: {
  summary: MonteCarloSummary
  modelLabel: string
  seed: number
  planId: string
}) {
  const pct = Math.round(summary.successRate * 100)
  const failing = summary.downsideRisk.failingPathCount
  const depletions = summary.depletionYearCounts
  const earliestDepletion = depletions.length > 0 ? depletions[0]!.year : null
  const medianDepletion = (() => {
    if (failing === 0) return null
    let seen = 0
    for (const row of depletions) {
      seen += row.count
      if (seen >= failing / 2) return row.year
    }
    return depletions[depletions.length - 1]?.year ?? null
  })()
  // "First decade" = the 10th projected year (or the last year on short plans).
  const decade = summary.fan[Math.min(9, summary.fan.length - 1)]
  const precision = summary.pathCount >= 10_000 ? '±0.5' : '±1.5'

  return (
    <details className="ss-explainer">
      <summary>Why this number?</summary>
      <p>
        <strong>What it counts.</strong> {pct}% means investable assets lasted to the end of the plan in{' '}
        {(summary.pathCount - failing).toLocaleString()} of the {summary.pathCount.toLocaleString()} simulated markets
        ({failing.toLocaleString()} depleted early). It is a statistic about this model of your plan, not a
        probability about your actual life.
      </p>
      <p>
        <strong>How the markets were made.</strong> Each path re-runs your full year-by-year projection (taxes, RMDs,
        IRMAA, withdrawals, everything) under markets generated by the <strong>{modelLabel}</strong> model
        (seed {seed}, reproducible). Your expected returns and inflation from{' '}
        <Link to={`/plan/${planId}/assumptions-card`}>your assumptions</Link> are the center of the distribution; the
        model only shapes the variation around them. At {summary.pathCount.toLocaleString()} paths the success rate is
        good to about {precision} points, so treat small differences between runs as noise.
      </p>
      {failing > 0 ? (
        <p>
          <strong>Which years drive it.</strong> Failing paths first run out between {earliestDepletion} and{' '}
          {depletions[depletions.length - 1]!.year}
          {medianDepletion !== null ? ` (median ${medianDepletion})` : ''}. See the depletion chart below for the full
          curve. Early depletions usually trace to weak markets in the first retirement decade: by {decade?.year}, the
          worst 10% of paths hold {fmtMoneyCompact(decade?.p10 ?? 0)} versus a median of{' '}
          {fmtMoneyCompact(decade?.p50 ?? 0)}. The same spending drawn from that smaller base is what sinks those
          paths (sequence-of-returns risk).
        </p>
      ) : (
        <p>
          <strong>Which years drive it.</strong> No simulated path depleted. The spread is still real: by{' '}
          {decade?.year}, the worst 10% of paths hold {fmtMoneyCompact(decade?.p10 ?? 0)} versus a median of{' '}
          {fmtMoneyCompact(decade?.p50 ?? 0)}.
        </p>
      )}
      <p>
        <strong>What would change it.</strong> The number moves with your assumptions, the model choice, spending, and
        retirement timing. That's why identical plans score differently across tools. To see exactly what this run
        assumed, open <Link to={`/plan/${planId}/assumptions-card`}>the assumptions card</Link>; to see how the engine
        itself is checked, see <Link to="/how-tested">how RetireGolden is tested</Link>.
      </p>
    </details>
  )
}

/**
 * Surfaces the exact-ledger tournament behind an optimizer recommendation:
 * the objective it was ranked by, every simple candidate it beat (with dollar
 * margins on the full projection), and how the winner was refined. Acceptance
 * (step 3): every recommendation shows its beaten alternatives and margins.
 */
export function WhyRecommendationPanel({
  tournament,
  objectiveLabel,
}: {
  tournament: ExactLedgerTournamentSummary
  objectiveLabel: string
}) {
  const estateObjective = tournament.policyId === 'max-after-tax-estate'
  const noWinner = tournament.winnerSource === 'none'
  // Estate deltas are the ranking metric only under the estate objective; for
  // other objectives keep the tournament's fixed generation order rather than
  // presenting an estate sort as the hierarchy.
  const candidates = estateObjective
    ? [...tournament.candidates].sort((a, b) => b.afterTaxEstateDelta - a.afterTaxEstateDelta)
    : tournament.candidates
  const winnerDelta = tournament.winnerValidation?.afterTaxEstateDelta ?? 0
  // Runner-up = best recommendation-eligible challenger. Candidates that
  // shorten how long the money lasts are hard-rejected by every objective, so
  // a higher estate delta on one of those is not a "next-best alternative".
  const runnerUp = tournament.candidates
    .filter((c) => c.id !== tournament.winnerCandidateId && c.moneyLastsYearsDelta >= 0)
    .reduce<(typeof tournament.candidates)[number] | null>(
      (best, c) => (best === null || c.afterTaxEstateDelta > best.afterTaxEstateDelta ? c : best),
      null,
    )
  const marginOverRunnerUp =
    runnerUp === null
      ? null
      : tournament.winnerSource === 'incumbent'
        ? -runnerUp.afterTaxEstateDelta
        : winnerDelta - runnerUp.afterTaxEstateDelta
  // Only claim "ahead by $X" when it is true on the metric being quoted.
  const showMargin = !noWinner && estateObjective && marginOverRunnerUp !== null && marginOverRunnerUp > 0

  const winnerPhrase =
    tournament.winnerSource === 'milp'
      ? "the solver's schedule"
      : (tournament.winnerLabel ?? 'the recommendation')
  const displayedMilpValidation =
    tournament.winnerSource === 'milp'
      ? tournament.winnerValidation
      : tournament.retirementActionReadinessVeto?.vetoedWinnerSource === 'milp'
        ? tournament.retirementActionReadinessVeto.vetoedValidation
        : null

  return (
    <details className="ss-explainer">
      <summary>Why this recommendation?</summary>
      {tournament.retirementActionReadinessVeto ? (
        <p>
          Every candidate below was re-run through your full year-by-year projection and ranked by{' '}
          <strong>{objectiveLabel}</strong>
          {estateObjective ? '' : ' (the estate deltas shown are context, not the ranking metric)'}.{' '}
          <strong>A calculated winner cleared the selected objective but was withheld pending account allocation.</strong>
        </p>
      ) : noWinner ? (
        <p>
          Every candidate below was re-run through your full year-by-year projection and ranked by{' '}
          <strong>{objectiveLabel}</strong>
          {estateObjective ? '' : ' (the estate deltas shown are context, not the ranking metric)'}.{' '}
          <strong>None cleared the recommendation threshold</strong>, so no schedule is recommended. The table shows
          what was considered and why nothing won.
        </p>
      ) : (
        <p>
          Every candidate below was re-run through your full year-by-year projection and ranked by{' '}
          <strong>{objectiveLabel}</strong>
          {estateObjective ? '' : ' (the estate deltas shown are context, not the ranking metric)'}. No candidate is
          recommended off the solver's simplified model alone. The winner is <strong>{winnerPhrase}</strong>
          {showMargin ? (
            <>
              , ahead of the next-best eligible alternative by <strong>{fmtMoney(marginOverRunnerUp!)}</strong> of
              projected after-tax estate
            </>
          ) : null}
          {tournament.winnerSource === 'candidate' && tournament.marginOverMilpDollars > 0
            ? `, and it beat the solver's own schedule by ${fmtMoney(tournament.marginOverMilpDollars)}`
            : ''}
          .{tournament.searchRefined ? ` A bounded local search (${tournament.searchSimulations} extra full-projection runs) then fine-tuned the winning schedule's per-year amounts.` : ''}
        </p>
      )}
      {tournament.acaActionabilityVeto ? (
        <p>
          <strong>Why nothing qualified.</strong> {acaVetoExplanation(tournament.acaActionabilityVeto)}
        </p>
      ) : null}
      {tournament.retirementActionReadinessVeto ? (
        <p>
          <strong>Why the calculated winner was withheld.</strong>{' '}
          {retirementActionReadinessVetoExplanation(
            tournament.retirementActionReadinessVeto,
            tournament.retirementActionPromotion,
          )}
        </p>
      ) : null}
      <div className="year-table-wrap" style={{ border: 'none' }}>
        <table className="compare-table">
          <thead>
            <tr>
              <th>Alternative considered</th>
              <th>Conversions executed</th>
              <th>After-tax estate</th>
              <th>Lifetime tax</th>
              <th>Money lasts</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                Your current plan (baseline)
                {tournament.winnerSource === 'incumbent' &&
                tournament.retirementActionReadinessVeto === null ? (
                  <strong> (winner)</strong>
                ) : ''}
              </td>
              <td>—</td>
              <td>±$0</td>
              <td>±$0</td>
              <td>—</td>
            </tr>
            {displayedMilpValidation ? (
              <tr>
                <td>
                  Solver's schedule (post-processed)
                  {tournament.winnerSource === 'milp' ? (
                    <strong> (winner)</strong>
                  ) : (
                    <em className="muted"> ({RETIREMENT_ACTION_READINESS_VETO_ROW_NOTE})</em>
                  )}
                </td>
                <td>{fmtMoneyCompact(displayedMilpValidation.executedConversionTotal)}</td>
                <td>{fmtSignedMoney(displayedMilpValidation.afterTaxEstateDelta)}</td>
                <td>{fmtSignedMoney(displayedMilpValidation.lifetimeTaxDelta)}</td>
                <td>
                  {displayedMilpValidation.moneyLastsYearsDelta === 0
                    ? 'unchanged'
                    : `${displayedMilpValidation.moneyLastsYearsDelta > 0 ? '+' : ''}${displayedMilpValidation.moneyLastsYearsDelta} yr`}
                </td>
              </tr>
            ) : null}
            {candidates.map((c) => (
              <tr key={c.id}>
                <td>
                  {c.label}
                  {c.id === tournament.winnerCandidateId ? <strong> (winner)</strong> : ''}
                  {tournament.acaActionabilityVeto?.vetoedCandidateIds.includes(c.id) ? (
                    <em className="muted"> ({ACA_VETO_ROW_NOTE})</em>
                  ) : null}
                  {tournament.retirementActionReadinessVeto?.vetoedCandidateId === c.id ? (
                    <em className="muted"> ({RETIREMENT_ACTION_READINESS_VETO_ROW_NOTE})</em>
                  ) : null}
                </td>
                <td>{fmtMoneyCompact(c.executedConversionTotal)}</td>
                <td>{fmtSignedMoney(c.afterTaxEstateDelta)}</td>
                <td>{fmtSignedMoney(c.lifetimeTaxDelta)}</td>
                <td>{c.moneyLastsYearsDelta === 0 ? 'unchanged' : `${c.moneyLastsYearsDelta > 0 ? '+' : ''}${c.moneyLastsYearsDelta} yr`}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="field-hint" style={{ margin: '0.4rem 0 0' }}>
        Deltas are versus your current plan, measured on the full projection (heir tax on pre-tax balances included).
        Candidates that shorten how long the money lasts are rejected regardless of estate gain. The solver's own
        schedule competes too; it only supplies the recommendation when nothing simpler beats it (and appears above
        when it wins). See <Link to="/how-tested">how RetireGolden is tested</Link> for the harnesses behind this
        pipeline.
      </p>
    </details>
  )
}
