/**
 * "Why this number" panels (trust-and-transparency-layer, steps 2–3):
 * expandable explainers that trace the two probabilistic headline outputs —
 * the Monte Carlo success % and the optimizer recommendation — to their
 * method, inputs, and the evidence already computed for them. Pure rendering
 * over existing payloads; no engine work happens here.
 */

import { Link } from 'react-router-dom'

import type { MonteCarloSummary } from '../engine/montecarlo/run'
import type { ExactLedgerTournament } from '../engine/projection/optimizePlan'
import { fmtMoney, fmtMoneyCompact } from './format'

function fmtSignedMoney(v: number): string {
  return `${v >= 0 ? '+' : '−'}${fmtMoney(Math.abs(v))}`
}

/**
 * Decomposes the success gauge: what counts as success, how the markets were
 * generated (model, paths, seed, precision), which ledger years the failing
 * paths actually deplete in, and how wide the first decade's outcomes spread
 * (sequence-of-returns sensitivity). Everything renders from the existing
 * `MonteCarloSummary`.
 */
export function WhySuccessPanel({
  summary,
  modelLabel,
  seed,
  planId,
}: {
  summary: MonteCarloSummary
  modelLabel: string
  seed: number
  planId: string
}) {
  const pct = Math.round(summary.successRate * 100)
  const failing = summary.downsideRisk.failingPathCount
  const depletions = summary.depletionYearCounts
  const earliestDepletion = depletions.length > 0 ? depletions[0]!.year : null
  const medianDepletion = (() => {
    if (failing === 0) return null
    let seen = 0
    for (const row of depletions) {
      seen += row.count
      if (seen >= failing / 2) return row.year
    }
    return depletions[depletions.length - 1]?.year ?? null
  })()
  // "First decade" = the 10th projected year (or the last year on short plans).
  const decade = summary.fan[Math.min(9, summary.fan.length - 1)]
  const precision = summary.pathCount >= 10_000 ? '±0.5' : '±1.5'

  return (
    <details className="ss-explainer">
      <summary>Why this number?</summary>
      <p>
        <strong>What it counts.</strong> {pct}% means investable assets lasted to the end of the plan in{' '}
        {(summary.pathCount - failing).toLocaleString()} of the {summary.pathCount.toLocaleString()} simulated markets
        ({failing.toLocaleString()} depleted early). It is a statistic about this model of your plan — not a
        probability about your actual life.
      </p>
      <p>
        <strong>How the markets were made.</strong> Each path re-runs your full year-by-year projection — taxes, RMDs,
        IRMAA, withdrawals, everything — under markets generated by the <strong>{modelLabel}</strong> model
        (seed {seed}, reproducible). Your expected returns and inflation from{' '}
        <Link to={`/plan/${planId}/assumptions-card`}>your assumptions</Link> are the center of the distribution; the
        model only shapes the variation around them. At {summary.pathCount.toLocaleString()} paths the success rate is
        good to about {precision} points, so treat small differences between runs as noise.
      </p>
      {failing > 0 ? (
        <p>
          <strong>Which years drive it.</strong> Failing paths first run out between {earliestDepletion} and{' '}
          {depletions[depletions.length - 1]!.year}
          {medianDepletion !== null ? ` (median ${medianDepletion})` : ''} — see the depletion chart below for the full
          curve. Early depletions usually trace to weak markets in the first retirement decade: by {decade?.year}, the
          worst 10% of paths hold {fmtMoneyCompact(decade?.p10 ?? 0)} versus a median of{' '}
          {fmtMoneyCompact(decade?.p50 ?? 0)} — the same spending drawn from that smaller base is what sinks those
          paths (sequence-of-returns risk).
        </p>
      ) : (
        <p>
          <strong>Which years drive it.</strong> No simulated path depleted. The spread is still real: by{' '}
          {decade?.year}, the worst 10% of paths hold {fmtMoneyCompact(decade?.p10 ?? 0)} versus a median of{' '}
          {fmtMoneyCompact(decade?.p50 ?? 0)}.
        </p>
      )}
      <p>
        <strong>What would change it.</strong> The number moves with your assumptions, the model choice, spending, and
        retirement timing — that's why identical plans score differently across tools. To see exactly what this run
        assumed, open <Link to={`/plan/${planId}/assumptions-card`}>the assumptions card</Link>; to see how the engine
        itself is checked, see <Link to="/how-tested">how RetireGolden is tested</Link>.
      </p>
    </details>
  )
}

/**
 * Surfaces the exact-ledger tournament behind an optimizer recommendation:
 * the objective it was ranked by, every simple candidate it beat (with dollar
 * margins on the full projection), and how the winner was refined. Acceptance
 * (step 3): every recommendation shows its beaten alternatives and margins.
 */
export function WhyRecommendationPanel({
  tournament,
  objectiveLabel,
}: {
  tournament: ExactLedgerTournament
  objectiveLabel: string
}) {
  const estateObjective = tournament.policyId === 'max-after-tax-estate'
  const noWinner = tournament.winnerSource === 'none'
  // Estate deltas are the ranking metric only under the estate objective; for
  // other objectives keep the tournament's fixed generation order rather than
  // presenting an estate sort as the hierarchy.
  const candidates = estateObjective
    ? [...tournament.candidates].sort((a, b) => b.afterTaxEstateDelta - a.afterTaxEstateDelta)
    : tournament.candidates
  const winnerDelta = tournament.winnerValidation?.afterTaxEstateDelta ?? 0
  // Runner-up = best recommendation-eligible challenger. Candidates that
  // shorten how long the money lasts are hard-rejected by every objective, so
  // a higher estate delta on one of those is not a "next-best alternative".
  const runnerUp = tournament.candidates
    .filter((c) => c.id !== tournament.winnerCandidateId && c.moneyLastsYearsDelta >= 0)
    .reduce<(typeof tournament.candidates)[number] | null>(
      (best, c) => (best === null || c.afterTaxEstateDelta > best.afterTaxEstateDelta ? c : best),
      null,
    )
  const marginOverRunnerUp =
    runnerUp === null
      ? null
      : tournament.winnerSource === 'incumbent'
        ? -runnerUp.afterTaxEstateDelta
        : winnerDelta - runnerUp.afterTaxEstateDelta
  // Only claim "ahead by $X" when it is true on the metric being quoted.
  const showMargin = !noWinner && estateObjective && marginOverRunnerUp !== null && marginOverRunnerUp > 0

  const winnerPhrase =
    tournament.winnerSource === 'milp'
      ? "the solver's schedule"
      : (tournament.winnerLabel ?? 'the recommendation')

  return (
    <details className="ss-explainer">
      <summary>Why this recommendation?</summary>
      {noWinner ? (
        <p>
          Every candidate below was re-run through your full year-by-year projection and ranked by{' '}
          <strong>{objectiveLabel}</strong>
          {estateObjective ? '' : ' (the estate deltas shown are context, not the ranking metric)'}.{' '}
          <strong>None cleared the recommendation threshold</strong>, so no schedule is recommended — the table shows
          what was considered and why nothing won.
        </p>
      ) : (
        <p>
          Every candidate below was re-run through your full year-by-year projection and ranked by{' '}
          <strong>{objectiveLabel}</strong>
          {estateObjective ? '' : ' (the estate deltas shown are context, not the ranking metric)'} — no candidate is
          recommended off the solver's simplified model alone. The winner is <strong>{winnerPhrase}</strong>
          {showMargin ? (
            <>
              , ahead of the next-best eligible alternative by <strong>{fmtMoney(marginOverRunnerUp!)}</strong> of
              projected after-tax estate
            </>
          ) : null}
          {tournament.winnerSource === 'candidate' && tournament.marginOverMilpDollars > 0
            ? `, and it beat the solver's own schedule by ${fmtMoney(tournament.marginOverMilpDollars)}`
            : ''}
          .{tournament.searchRefined ? ` A bounded local search (${tournament.searchSimulations} extra full-projection runs) then fine-tuned the winning schedule's per-year amounts.` : ''}
        </p>
      )}
      <div className="year-table-wrap" style={{ border: 'none' }}>
        <table className="compare-table">
          <thead>
            <tr>
              <th>Alternative considered</th>
              <th>Conversions executed</th>
              <th>After-tax estate</th>
              <th>Lifetime tax</th>
              <th>Money lasts</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                Your current plan (baseline)
                {tournament.winnerSource === 'incumbent' ? <strong> — winner</strong> : ''}
              </td>
              <td>—</td>
              <td>±$0</td>
              <td>±$0</td>
              <td>—</td>
            </tr>
            {tournament.winnerSource === 'milp' && tournament.winnerValidation ? (
              <tr>
                <td>
                  Solver's schedule (post-processed)<strong> — winner</strong>
                </td>
                <td>{fmtMoneyCompact(tournament.winnerValidation.executedConversionTotal)}</td>
                <td>{fmtSignedMoney(tournament.winnerValidation.afterTaxEstateDelta)}</td>
                <td>{fmtSignedMoney(tournament.winnerValidation.lifetimeTaxDelta)}</td>
                <td>
                  {tournament.winnerValidation.moneyLastsYearsDelta === 0
                    ? 'unchanged'
                    : `${tournament.winnerValidation.moneyLastsYearsDelta > 0 ? '+' : ''}${tournament.winnerValidation.moneyLastsYearsDelta} yr`}
                </td>
              </tr>
            ) : null}
            {candidates.map((c) => (
              <tr key={c.id}>
                <td>
                  {c.label}
                  {c.id === tournament.winnerCandidateId ? <strong> — winner</strong> : ''}
                </td>
                <td>{fmtMoneyCompact(c.executedConversionTotal)}</td>
                <td>{fmtSignedMoney(c.afterTaxEstateDelta)}</td>
                <td>{fmtSignedMoney(c.lifetimeTaxDelta)}</td>
                <td>{c.moneyLastsYearsDelta === 0 ? 'unchanged' : `${c.moneyLastsYearsDelta > 0 ? '+' : ''}${c.moneyLastsYearsDelta} yr`}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="field-hint" style={{ margin: '0.4rem 0 0' }}>
        Deltas are versus your current plan, measured on the full projection (heir tax on pre-tax balances included).
        Candidates that shorten how long the money lasts are rejected regardless of estate gain. The solver's own
        schedule competes too; it only supplies the recommendation when nothing simpler beats it (and appears above
        when it wins). See <Link to="/how-tested">how RetireGolden is tested</Link> for the harnesses behind this
        pipeline.
      </p>
    </details>
  )
}
