export type CoverageAttestationStatus = 'registered' | 'partial' | 'rule-free' | 'unswept'

export interface CoverageAttestation {
  readonly status: CoverageAttestationStatus
  /** ISO date of the sweep that assigned this status; null only while unswept. */
  readonly sweptOn: string | null
  /** For 'partial': the residual unregistered claims, one short clause each. */
  readonly note: string | null
}

/**
 * An attestation is a dated, re-falsifiable sweep claim with the same epistemic
 * standing as a registry record's verifiedOn: it records what a reviewer
 * checked, not a permanent conclusion.
 *
 * - registered — every claim found in the file is represented by a rule.
 * - partial — the file was swept, but note names residual unregistered claims.
 * - rule-free — the file was swept and contains no claims requiring a rule.
 * - unswept — the file has not received a coverage sweep (retained for re-sweeps;
 *   the 2026-08-24 baseline sweep closed the grandfather window).
 *
 * BASELINE_UNSWEPT is frozen empty: the baseline sweep is complete and no file
 * may hold status unswept.
 */
export const COVERAGE_ATTESTATIONS: Readonly<Record<string, CoverageAttestation>> = Object.freeze({
  'actions/aggregateRothConversionOwnerAllocation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'RMD-before-conversion ordering/snapshot registered under treas-reg-1-408A-4-a-6-rmd-precedes-conversion' }),
  'actions/annualHsaOpeningAuthority.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaPenaltyEvaluation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaPhysicalMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaReimbursementLedger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaTreatmentBindingCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualIraBasisAllocation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualLiabilityRunIdentity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualOwnedNonRothIraPoolCapacity.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'QCD pool restricted to donor-owned non-Roth IRAs; no record' }),
  'actions/annualQcdActionExecutionEvidence.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/annualQcdDeductionTreatmentCoordinator.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/annualQcdDerivedTaxCharacter.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-25', note: 'Owned-source eligibility gate; no record; QCD taxable/excludable/basis partition; no record' }),
  'actions/annualQcdExecution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdExecutionPrerequisite.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdItemizedLiabilityReconciliation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdItemizedSection170Ledger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdPhysicalExecution.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'QCD pool restricted to owned traditional IRAs, excluding inherited/Roth; no record' }),
  'actions/annualQcdResidualForm8606.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-25', note: 'Residual line-7/line-8 pro-rata reconciliation; no record' }),
  'actions/annualQcdStandardSection170pLedger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdTaxCharacterPostPass.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdUnifiedTransactionFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualRetirementActionMovementCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualRetirementActionPublication.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-27', note: null }),
  'actions/annualRetirementPhysicalEventInventory.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Inherited-RMD regime; owner-RMD start age; spouse-as-own transition; annuity/Form 8606 treatment; direct-trustee QCD origin; no record' }),
  'actions/annualSection68ItemizedDeduction.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiarySpousalElectionStatus.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualPhysicalTransaction.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualPlanApplication.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Beneficiary-owned inherited traditional-IRA/death-year source gate; no record' }),
  'actions/beneficiaryTraditionalIraAnnualRuntimeCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualSimulatorDelta.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/beneficiaryTraditionalIraDeathPenalty.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/beneficiaryTraditionalIraMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdActionIdentity.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Residual-RMD source restricted to beneficiary-owned inherited traditional IRA; no record' }),
  'actions/beneficiaryTraditionalIraResidualRmdAllocation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdAnnualRefinalization.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Form 8606 line-7/line-8 residual rebuild and forced-zero line 8; no record' }),
  'actions/beneficiaryTraditionalIraResidualRmdChronology.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdPhysicalTransaction.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraWithdrawalCharacter.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Inherited-IRA line-8 conversion/spousal-conversion refusal; no record' }),
  'actions/civilDate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/contract.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/conversionLinkedWithdrawalGroup.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/conversionLinkedWithdrawalGroupExecution.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/conversionTaxFundingEvidence.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/exactCentProRata.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/execution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'equity-compensation execution character registered as irc-83-a-equity-compensation-execution-character (approximated), which names this file; the 2026-08-25 note predated that record by a day' }),
  'actions/identity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/money.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualCandidateCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualCandidateTransaction.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Owned traditional/SEP/SIMPLE IRA source scope and line-7 movement staging; no record' }),
  'actions/ownedNonRothIraAnnualFilingEvidence.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Prior-year contribution window covered; owner-wide non-inherited IRA pool and January-1 opening-basis requirement; no record' }),
  'actions/ownedNonRothIraAnnualFilingSourceResolver.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Filing source restricted to owned non-inherited traditional IRA pool; no record' }),
  'actions/ownedNonRothIraAnnualFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualPhysicalTransaction.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Form 8606 line-7/line-8 categorization; same-owner Roth-IRA destination; QCD charitable-debit scope; no record' }),
  'actions/ownedNonRothIraAnnualPlanCoordinator.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Owner-wide pool excludes inherited IRAs; Form 8606 numerator/denominator and line-7/line-8 stacking; exact age-59½ threshold; no record' }),
  'actions/ownedNonRothIraAnnualPostCandidateEvidence.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Contribution window covered; Form 8606 lines 1/4/6/7/9, owner-wide pool, and explicit zero line 8; no record' }),
  'actions/ownedNonRothIraMovementCandidate.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Source constrained to owned traditional/SEP/SIMPLE IRAs; positive withdrawals emitted as line 7; no record' }),
  'actions/ownedNonRothIraPenaltyPrerequisite.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Age, 10%/25% rates, disability, SEPP, SIMPLE period, and scope covered; death exception rejected through owner-alive evidence; no record' }),
  'actions/ownedNonRothIraSeppAnnualReconciliation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraSeppCurrentPaymentCandidate.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/planBalanceAdapter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'named by the sub-cent discharge record; planDollarsMoveNoLedgerCent defines when that rule applies' }),
  'actions/qcdDeductibleContributionOffset.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/reasons.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/retirementActionCandidateIdentityAllocator.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Conversion source and destination vehicle restrictions are registered under irc-408A-d-3-B-conversion-destination-must-be-a-roth-ira; QCD source-IRA restrictions remain open because no matching QCD record fits' }),
  'actions/retirementActionManualReview.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Replacement source-owner and Roth-destination eligibility checks are registered under irc-408A-d-3-B-conversion-destination-must-be-a-roth-ira' }),
  'actions/rothConversionExecution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Positive-basis deferred character is registered under irc-408-d-2-annual-pro-rata-basis and direct conversion vehicle gates under irc-408A-d-3-B-conversion-destination-must-be-a-roth-ira' }),
  'actions/structuralId.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/taxableWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/traditionalEmployerPlanPenaltyPrerequisite.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Rule of 55, employer-SEPP, permitted methods, public-safety and recapture covered; age-59½ threshold, 10% rate, disability waiver lack records' }),
  'actions/traditionalEmployerPlanWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'allocation/assetClasses.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/annuitization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/decisionFixtures.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'fixture builder with no non-test importer; the 73 is a comment on a date of birth, not an operative threshold - same footing as testing/planFixtures.ts' }),
  'decisions/evaluateCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/generators.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'QLAC 85 ceiling registered via treas-reg-1-401-a-9-6-q-1-ii-qlac-commences-by-the-85th-birthday naming annuityPurchaseGenerator; the bracket-target list is a search-space choice, but SS_GRID_CLAIM_AGES encodes the statutory 62-70 worker claiming window and stays a residual with claimFactor.ts' }),
  'decisions/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/insightsAdapter.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/objectives.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'bridge filter consumes rmdStartAgeForBirthYear (cohort defect fixed 2026-08-29); registered via irc-401-a-9-C-v-applicable-age naming bridgeYearFilter' }),
  'decisions/ordinaryWithdrawalCandidateAdapter.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/pensionElection.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Tax-free direct rollover into traditional IRA; no record' }),
  'decisions/qcdCandidateAdapter.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/retirementActionCandidateSchedule.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/rothConversionCandidateAdapter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Same-owner Roth destination and dated-intent gate are registered under irc-408A-d-3-B-conversion-destination-must-be-a-roth-ira' }),
  'decisions/search.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/spendingSolver.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/spiaQuotes.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/stochastic.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/swrComparator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/tournament.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/types.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/acaThresholdProximity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/annuitizationHeadroom.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/assetLocation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/hecmBufferCandidate.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'returns null under age 62, the statutory HECM minimum age (12 U.S.C. 1715z-20(b)). Held partial pending an owner scope decision: the registry has held tax statutes only, and admitting housing law is a domain expansion the sweep does not decide' }),
  'insights/detectors/incomeFloorFunded.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/irmaaTierEdge.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/lawPackDrift.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/missingDataBasis.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'the section 121 coverage classification is registered via irc-121-a-b-principal-residence-eligibility-tests naming this detector (another independent implementation beside tax/propertySale.ts and the simulate path - consolidation candidate). Residual: the detector also gates on ROTH_QUALIFIED_AGE independently, and the Roth 59½ records do not name it' }),
  'insights/detectors/pensionElectionPending.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/qcdEfficiency.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/rothBridgeHeadroom.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'the hardcoded 73 the prior note flagged is fixed (2026-08-29): the detector consumes rmdStartAgeForBirthYear and is registered via irc-401-a-9-C-v-applicable-age' }),
  'insights/detectors/spendingGuardrails.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/spendingHeadroom.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/ssBridgeGap.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/ssClaimMilestone.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Re-derives SS entitlement/eligibility (former-spouse gates, family max, payable months) beyond registry gaps for maritalBenefits/nra' }),
  'insights/detectors/stalePlanData.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/stateRelocation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/widowsPenalty.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/parsePlanUpdatedAtIso.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/registry.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/runInsights.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/types.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/annualPassAttemptDriver.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/counterfactualAnnualLiability.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/iraAnnuityContractValue.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'internal/ownedNonRothIraAnnualAttemptSettlement.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: '408(d)(3)(A)(i) same-owner conversion identity; no record' }),
  'internal/ownedNonRothIraAnnualReplayPublication.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/ownedNonRothIraContiguousReplay.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'internal/ownedNonRothIraReplayIdentity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/ownedNonRothIraRuntimeSourceSeries.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Records cover QCD and annuity aggregation; residual 408(d)(3)(A)(i) same-owner conversion, 408(d)(3)(C) inherited-rollover bar, and RMD-before-conversion ordering' }),
  'internal/simulatorAnnualPassValueBindingKeys.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'ladder/bridge.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Bridge cannot start before SS age 62; uses claimFactor/PIA sizing without naming record' }),
  'ladder/fedInvest.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'ladder/fundedRatio.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'ladder/ladderMath.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'TIPS OID/deflation and §171 premium absence registered (treas-reg-1-1275-7-f-1-deflation-adjustment-income, treas-reg-1-1275-7-f-2-deflation-basis-decrease-not-modeled, treas-reg-1-1275-7-f-3-tips-acquisition-premium, irc-171-tips-bond-premium-amortization); statutory 0.125% min coupon and par-yield pricing conventions remain' }),
  'longevity/ssaPeriod2022.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'SSA 2022 period table provenance/vintage unregistered; statutory-use records name consumers' }),
  'longevity/types.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'model/migrations.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Lump-sum election load repairs; inherited qualified-annuity premium retarget/stand-down beyond annuity-start ceiling records' }),
  'model/plan.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Inherited IRA regime parse rules; spouse J&S RMD gate; 403(b) aggregation; SEPP schema; Roth inherited rules; HSA/stateMove/retirement-action eligibility gates' }),
  'model/retirementActionAnnualTaxFacts.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'April filing deadline w/ weekend & Emancipation Day adjustments; post-year IRA contribution window invariants; record names other files' }),
  'montecarlo/frontiers.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/historicalReturns.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/historicalSuites.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/ltcShock.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/marketModels.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/mortality.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'SSA 2022 period-table q(x) derivation for stochastic longevity MC; separate from treas-reg annuitization record' }),
  'montecarlo/riskBasedGuardrails.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/rng.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/run.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/sharedPaths.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/survival.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'params/data/realYieldCurve2026.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'Treasury market-data snapshot; provenance in params/provenance.ts, not statute' }),
  'params/data/year2026.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'params/index.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Trustees default SS haircut (2034, 17%); indexFederalTaxPack uses plan inflation not C-CPI-U; convention only in records naming federalTax.ts' }),
  'params/provenance.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'params/state/data/year2026.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'params/state/index.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'params/state/types.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'types only; named by records for the shapes they define' }),
  'params/types.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'types only; named by records for the shapes they define' }),
  'projection/annualCashFlowCapture.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Form 8606 basis, QCD exclusion, annuity and penalty character composition; no record' }),
  'projection/annualCashFlowIds.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualCashFlowReconciliation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualCashFlowShortfallAttribution.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualCashFlowYearSites.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualPassTransaction.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualRetirementRuntimeJournal.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annuityForms.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'projection/beneficiaryTraditionalIraAnnualPassConsumer.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/compare.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'after-tax estate haircuts incl. taxable step-up registered (irc-1014-a-1-basis-at-death-fair-market-value); Form 8606 basis exclusion, spousal rollover, HSA non-spouse income remain' }),
  'projection/employerRothCatchUp.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'projection/flatTax.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'V1 placeholder whose only importers are test files, so the IRC 86 85 percent inclusion it computes never reaches a user-facing number; kept partial rather than rule-free so the claim stays visible if the file ever gains a production consumer' }),
  'projection/internal/legacyAggregateDecisionCalculation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/moneyTolerance.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'half-cent funding fixed-point tolerance; numerical guard, not statute' }),
  'projection/optimizePlan.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'Flat 15% LTCG LP rate registered (irc-1-h-optimizer-flat-fifteen-percent-preferential-rate); other optimizer linearizations remain unregistered' }),
  'projection/optimizerAggregateConversionPromotion.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'RMD-first ordering, employer-plan distributability, and same-owner Roth destination are registered under treas-reg-1-408A-4-a-6-rmd-precedes-conversion, irc-401-k-2-B-i-employer-plan-conversion-source-not-gated-by-distributability, and irc-408A-d-3-B-conversion-destination-must-be-a-roth-ira' }),
  'projection/optimizerAggregateConversionPromotionRun.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/optimizerAllocatedCandidateComparison.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/optimizerExactLedgerComparison.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/ownedIraAnnualPhysicalTransactionInputs.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Form 8606 line-7/8 and QCD staging semantics; no record' }),
  'projection/ownedNonRothIraAnnualObservation.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'April-15/weekend/Emancipation-Day filing deadline; no record' }),
  'projection/relocation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/simulate.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-26', note: 'QCD/RMD/annuity/contribution/QLAC covered; residual 59½/HSA/Roth-five-year/Rule-of-55 proxies, inherited-Roth post-flip, Medicare age-65, HSA family-limit, spousal/survivor SS' }),
  'projection/types.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'rmd/applicableAge.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'named by treas-reg-1-401-a-9-5-d-1-ii-greater-of-employee-life-expectancy and, from 2026-08-29, by irc-401-a-9-C-v-applicable-age (applicableAgeAttainYears). Residual: the RBD April-1 arm, the 70½/July-1949 cohorts, and the born-1959 dual-age contest awaiting Announcement 2026-7' }),
  'rmd/jointLifeTable.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'rmd/rmd.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'rmd/rmdShortfallExcise.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'rules/coverageAttestations.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'registry/coverage tooling' }),
  'rules/coverageReport.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'registry/coverage tooling' }),
  'rules/describeRule.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'registry/coverage tooling' }),
  'rules/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'registry/coverage tooling' }),
  'rules/symbolLines.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-28', note: 'registry/coverage tooling' }),
  'rules/taxRuleRegistry.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'the record store itself; enforced by taxRuleRegistry.conformance.test.ts' }),
  'scenarios/actionRows.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/comparison.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/contract.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/patch.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/scenarios.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/taxOpportunityView.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/taxStrategyEvaluation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/taxStrategyEvaluationRegistryCheck.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/taxStrategyTradeoffs.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'schema/generate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'schema/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'schema/plan.v1.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'schema/plan.v2.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'schema/plan.v3.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'schema/plan.v4.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'schema/planSchemaMeta.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/benefitFactor.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/claimFactor.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Correction: usc-42-402-b-2-spousal-half-of-pia and poms-rs-00615-482-arf-crediting-months DO name this file; residual narrows to the worker 62y0m-70y0m claim window and DRC/ARF factor composition' }),
  'socialSecurity/disability.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-27', note: null }),
  'socialSecurity/familyMaximum.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/maritalBenefits.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Eligibility rules (10-yr divorce, 9-mo survivor marriage, age gates, remarriage forfeiture) have no records' }),
  'socialSecurity/nra.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-26', note: null }),
  'socialSecurity/piaFromEarnings.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'AIME pipeline (age 22–61 window, 5 lowest dropped, top-35 years, AWI indexing) not separately registered; the disability-freeze exclusion and post-entitlement recomputation base window ARE registered as approximations' }),
  'socialSecurity/ssaWageData.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/survivorBenefit.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'spending/abw.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'spending/flexibleGoals.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'spending/guardrails.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'spending/layers.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'spending/shapePresets.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'strategies/accountEligibility.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-25', note: 'SECURE 2020 gate portion of S2 treat-as-own election timing not registered to this file' }),
  'strategies/inheritedIra.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'strategies/iraBasis.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'strategies/optimizer.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'MILP prices brackets, IRMAA, ACA MAGI cap, RMD floors, §86 SS phase-in, LTCG; not registered here' }),
  'strategies/rothBasis.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'strategies/rothConversion.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Bracket/IRMAA/ACA FPL/senior-deduction sizing via computeFederalTax; no record names this file' }),
  'strategies/sepp.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'tax/aca.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'tax/aggregateBasisSale.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'tax/annualCharitableDeductionParameters.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: '§170(b)(1)(I) 0.5% floor, §170(b)(1)(G) 60% limit, §68 thresholds/rate; only §170(p) cap record names this file' }),
  'tax/federalTax.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-26', note: 'implements §86 SS inclusion, NIIT, AMT screen, senior-deduction phase-out, LTCG stacking with records naming it, but §170(b)(1)(I)(ii) category waterfall is applied only in the ledger file its record names' }),
  'tax/medicare.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'Part B/IRMAA premium path and Part B late-enrollment absence registered (usc-42-1395r-*, cfr-20-418-1205-1230-*); post-pack premiumScale (healthcare-inflation stand-in) remains' }),
  'tax/propertySale.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Personal-use capital loss nondeductible (gain floored at zero) remains unregistered. Correction: three section 121/1250 records DO name this file; the loss-floor clause specifically is the residual' }),
  'tax/stateTax.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'testing/money.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'testing/planFixtures.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'version.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'version.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
})

/** Grandfather window closed with the 2026-08-24 baseline sweep; must stay empty. */
export const BASELINE_UNSWEPT: readonly string[] = Object.freeze([])

