export type CoverageAttestationStatus = 'registered' | 'partial' | 'rule-free' | 'unswept'

export interface CoverageAttestation {
  readonly status: CoverageAttestationStatus
  /** ISO date of the sweep that assigned this status; null only while unswept. */
  readonly sweptOn: string | null
  /** For 'partial': the residual unregistered claims, one short clause each. */
  readonly note: string | null
}

/**
 * An attestation is a dated, re-falsifiable sweep claim with the same epistemic
 * standing as a registry record's verifiedOn: it records what a reviewer
 * checked, not a permanent conclusion.
 *
 * - registered — every claim found in the file is represented by a rule.
 * - partial — the file was swept, but note names residual unregistered claims.
 * - rule-free — the file was swept and contains no claims requiring a rule.
 * - unswept — the file has not received a coverage sweep (retained for re-sweeps;
 *   the 2026-08-24 baseline sweep closed the grandfather window).
 *
 * BASELINE_UNSWEPT is frozen empty: the baseline sweep is complete and no file
 * may hold status unswept.
 */
export const COVERAGE_ATTESTATIONS: Readonly<Record<string, CoverageAttestation>> = Object.freeze({
  'actions/aggregateRothConversionOwnerAllocation.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'same-owner pro-rata allocation long registered under irc-408-d-3-A-i; the RMD-before-conversion ordering it relies on is enforced upstream (resolveOwnerIraRmdSatisfaction), and this file consumes the post-RMD snapshot as a contract rather than enforcing it - that contract stays the residual' }),
  'actions/annualHsaOpeningAuthority.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaPenaltyEvaluation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaPhysicalMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaReimbursementLedger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaTreatmentBindingCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualIraBasisAllocation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualLiabilityRunIdentity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualOwnedNonRothIraPoolCapacity.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'QCD pool restricted to donor-owned non-Roth IRAs; no record' }),
  'actions/annualQcdActionExecutionEvidence.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/annualQcdDeductionTreatmentCoordinator.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/annualQcdDerivedTaxCharacter.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Owned-source eligibility arrives as typed AcceptedQcdSourceEligibilityEvidence - this module consumes what the QCD execution prerequisite evaluator enforces, and the 408(d)(8) source records are registered at that evaluator; the taxable/excludable/basis partition is registered under the composition-order and taxable-first records' }),
  'actions/annualQcdExecution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdExecutionPrerequisite.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdItemizedLiabilityReconciliation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdItemizedSection170Ledger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdPhysicalExecution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The account gate enforces owned-and-not-inherited IRA sourcing and the beneficiary and Roth 408(d)(8) source records name the stager; the ongoing SEP/SIMPLE exclusion is enforced and registered at the execution prerequisite evaluator' }),
  'actions/annualQcdResidualForm8606.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The residual pass keeps line-7 and line-8 pools distinct (registered under form-8606-lines-7-and-8-distinct-distribution-staging, which now names the stager) and consumes allocation evidence computed under the registered 408(d)(2) fraction' }),
  'actions/annualQcdStandardSection170pLedger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdTaxCharacterPostPass.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdUnifiedTransactionFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualRetirementActionMovementCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualRetirementActionPublication.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-27', note: null }),
  'actions/annualRetirementPhysicalEventInventory.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Inherited-RMD regime; owner-RMD start age; spouse-as-own transition; annuity/Form 8606 treatment; direct-trustee QCD origin; no record' }),
  'actions/annualSection68ItemizedDeduction.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiarySpousalElectionStatus.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualPhysicalTransaction.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualPlanApplication.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Beneficiary-owned inherited traditional-IRA/death-year source gate; no record' }),
  'actions/beneficiaryTraditionalIraAnnualRuntimeCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualSimulatorDelta.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/beneficiaryTraditionalIraDeathPenalty.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/beneficiaryTraditionalIraMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdActionIdentity.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Residual-RMD source restricted to beneficiary-owned inherited traditional IRA; no record' }),
  'actions/beneficiaryTraditionalIraResidualRmdAllocation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdAnnualRefinalization.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The line-7 rebuild with a forced-zero line 8 is registered under the lines-7-and-8 staging split and the inherited-rollover bar (a beneficiary pool can never carry conversions), both of which now name the refinalization' }),
  'actions/beneficiaryTraditionalIraResidualRmdChronology.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdPhysicalTransaction.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraWithdrawalCharacter.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'The nonzero-line-8 refusal mixes two things the reviewers rightly split: for a non-spouse beneficiary it is the 408(d)(3)(C)(i) bar, registered at that record\'s own enforcers, and for a spouse beneficiary a conversion after electing ownership is lawful but unsupported - the refusal reason names exactly that, so the engine-scope half stays the residual here' }),
  'actions/civilDate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/contract.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/conversionLinkedWithdrawalGroup.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/conversionLinkedWithdrawalGroupExecution.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/conversionTaxFundingEvidence.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/exactCentProRata.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/execution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'equity-compensation execution character registered as irc-83-a-equity-compensation-execution-character (approximated), which names this file; the 2026-08-25 note predated that record by a day' }),
  'actions/identity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/money.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualCandidateCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualCandidateTransaction.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The wrapper runs its own owned non-inherited gate (account.inherited must be undefined) and the pool-scope record now pins it; line semantics are registered where they are enforced, at the movement stager' }),
  'actions/ownedNonRothIraAnnualFilingEvidence.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Prior-year contribution window covered and the ownedIraPool filter is now pinned by the pool-scope record; the January-1 opening-basis anchor stays an engine convention (408(d)(2)(C) computes values as of the close of the year) and is the sole residual' }),
  'actions/ownedNonRothIraAnnualFilingSourceResolver.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The resolver computes the owned non-inherited pool itself (its account filter) and the pool-scope record now pins it; its remaining issues are binding and dedup integrity' }),
  'actions/ownedNonRothIraAnnualFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualPhysicalTransaction.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Same-owner Roth destination and designated-Roth vehicle refusal registered under irc-408-d-3-A-i and irc-408A-d-3-B, and line-7/line-8 categorization under form-8606-lines-7-and-8-distinct-distribution-staging; QCD charitable-debit scope remains unregistered' }),
  'actions/ownedNonRothIraAnnualPlanCoordinator.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'The owner-wide non-inherited pool filter and the out-of-pool line-8 refusal are registered under irc-408-d-2-A-owner-wide-non-inherited-ira-pool; the line-7/line-8 stacking composition and the exact age-59\u00bd threshold representation remain the residuals' }),
  'actions/ownedNonRothIraAnnualPostCandidateEvidence.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Pool completeness (every owned non-inherited sibling, employer/inherited/foreign refused) is registered under irc-408-d-2-A-owner-wide-non-inherited-ira-pool and the contribution window was already covered; the line 1/4/6/9 staging composition and the path\'s type-level explicit-zero line 8 remain the residuals' }),
  'actions/ownedNonRothIraMovementCandidate.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Line-7 staging registered under form-8606-line-7-owned-ira-movement-staging; the owned traditional/SEP/SIMPLE source gate is registered under irc-408-d-2-A-owner-wide-non-inherited-ira-pool, which pins the stager\'s source-evidence refusal' }),
  'actions/ownedNonRothIraPenaltyPrerequisite.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Age, 10%/25% rates, disability, SEPP, SIMPLE period and scope covered; the death exception is rejected through owner-alive evidence and irc-72-t-2-A-ii now names the evaluator' }),
  'actions/ownedNonRothIraSeppAnnualReconciliation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraSeppCurrentPaymentCandidate.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/planBalanceAdapter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'named by the sub-cent discharge record; planDollarsMoveNoLedgerCent defines when that rule applies' }),
  'actions/qcdDeductibleContributionOffset.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/reasons.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/retirementActionCandidateIdentityAllocator.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'conversion source and destination identity registered under irc-408-d-3-A-i, the inherited-source refusal under irc-408-d-3-C-i, and the named-action designated-Roth refusal under irc-408A-d-3-B (conversionDestinationIssue kind gate); QCD source-IRA restrictions remain open' }),
  'actions/retirementActionManualReview.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'replacement source-owner and Roth-destination identity checks registered under irc-408-d-3-A-i; the type gate here does not discriminate a designated Roth (that vehicle refusal lives in the identity allocator), and the QCD source-owner clause remains open' }),
  'actions/rothConversionExecution.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'ordering and inherited-bar records name executeRothConversions; the positive-basis deferred-character branch publishes null character for the downstream annual 408(d)(2) pass to resolve, and that deferral plus the direct-vehicle gates remain the residual' }),
  'actions/structuralId.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/taxableWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/traditionalEmployerPlanPenaltyPrerequisite.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Rule of 55, employer-SEPP, permitted methods, public-safety, recapture and the age-59½ threshold are registered records naming this file, and irc-72-t-2-A-iii now names the disability arm; the 10% rate application site for employer plans remains the residual' }),
  'actions/traditionalEmployerPlanWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'allocation/assetClasses.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/annuitization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/decisionFixtures.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'fixture builder with no non-test importer; the 73 is a comment on a date of birth, not an operative threshold - same footing as testing/planFixtures.ts' }),
  'decisions/evaluateCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/generators.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'QLAC 85 ceiling registered via treas-reg-1-401-a-9-6-q-1-ii-qlac-commences-by-the-85th-birthday; SS_GRID_CLAIM_AGES now registered under usc-42-402-worker-claim-window-62-to-70; the bracket-target list is a search-space choice, not a rule claim' }),
  'decisions/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/insightsAdapter.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/objectives.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'bridge filter consumes rmdStartAgeForBirthYear (cohort defect fixed 2026-08-29); registered via irc-401-a-9-C-v-applicable-age naming bridgeYearFilter' }),
  'decisions/ordinaryWithdrawalCandidateAdapter.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/pensionElection.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Tax-free direct rollover into traditional IRA; no record' }),
  'decisions/qcdCandidateAdapter.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/retirementActionCandidateSchedule.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/rothConversionCandidateAdapter.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'same-owner destination gate registered under irc-408-d-3-A-i; the dated-intent gate remains unregistered' }),
  'decisions/search.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/spendingSolver.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/spiaQuotes.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/stochastic.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/swrComparator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/tournament.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'decisions/types.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/acaThresholdProximity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/annuitizationHeadroom.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/assetLocation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/hecmBufferCandidate.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The age-62 gate is registered under usc-12-1715z-20-b-hecm-minimum-age-62 - the registry\'s first Title 12 record, admitted on the same enforcement test as its Title 42 and POMS records' }),
  'insights/detectors/incomeFloorFunded.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/irmaaTierEdge.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/lawPackDrift.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/missingDataBasis.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'The detector consumes the shared ROTH_QUALIFIED_AGE constant to scope its suggestion; the qualified-distribution rule itself is registered and enforced at the Roth basis records, which do not name this consumer' }),
  'insights/detectors/pensionElectionPending.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/qcdEfficiency.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/rothBridgeHeadroom.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'the hardcoded 73 the prior note flagged is fixed (2026-08-29): the detector consumes rmdStartAgeForBirthYear and is registered via irc-401-a-9-C-v-applicable-age' }),
  'insights/detectors/spendingGuardrails.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/spendingHeadroom.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/ssBridgeGap.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/ssClaimMilestone.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Re-derives SS entitlement/eligibility (former-spouse gates, family max, payable months) beyond registry gaps for maritalBenefits/nra' }),
  'insights/detectors/stalePlanData.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/stateRelocation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/detectors/widowsPenalty.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/parsePlanUpdatedAtIso.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/registry.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/runInsights.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'insights/types.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/annualPassAttemptDriver.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/counterfactualAnnualLiability.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/iraAnnuityContractValue.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'internal/ownedNonRothIraAnnualAttemptSettlement.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Its one statutory claim - the retired 408(d)(3)(A)(i) same-owner re-check - is enforced upstream in the runtime source series, where the record now pins it; this module itself enforces no rule and so is not named by any record' }),
  'internal/ownedNonRothIraAnnualReplayPublication.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/ownedNonRothIraContiguousReplay.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'internal/ownedNonRothIraReplayIdentity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'internal/ownedNonRothIraRuntimeSourceSeries.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'QCD and annuity aggregation were already covered; the same-owner conversion credit refusal (irc-408-d-3-A-i), the inherited-source bar (irc-408-d-3-C-i), and RMD-before-conversion phase ordering (treas-reg-1-408A-4-a-6) are now registered and pinned here' }),
  'internal/simulatorAnnualPassValueBindingKeys.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'ladder/bridge.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'The bridge sizes spending from age 62 to the claim age; the 62-70 worker window is registered under usc-42-402-worker-claim-window-62-to-70 at the claim factor, and this file calls that factor rather than enforcing the window itself' }),
  'ladder/fedInvest.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'ladder/fundedRatio.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'ladder/ladderMath.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'TIPS OID/deflation and §171 premium absence registered (treas-reg-1-1275-7-f-1-deflation-adjustment-income, treas-reg-1-1275-7-f-2-deflation-basis-decrease-not-modeled, treas-reg-1-1275-7-f-3-tips-acquisition-premium, irc-171-tips-bond-premium-amortization); statutory 0.125% min coupon and par-yield pricing conventions remain' }),
  'longevity/ssaPeriod2022.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Table provenance and vintage registered under ssa-table-4c6-period-life-table-vintage, approximated with the embedded 2022-period value pinned against the currently published 2023-period table' }),
  'longevity/types.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'model/migrations.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Lump-sum election load repairs; inherited qualified-annuity premium retarget/stand-down beyond annuity-start ceiling records' }),
  'model/plan.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Inherited IRA regime parse rules; spouse J&S RMD gate; 403(b) aggregation; SEPP schema; Roth inherited rules; HSA/stateMove/retirement-action eligibility gates' }),
  'model/retirementActionAnnualTaxFacts.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'April filing deadline w/ weekend & Emancipation Day adjustments; post-year IRA contribution window invariants; record names other files' }),
  'montecarlo/frontiers.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/historicalReturns.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/historicalSuites.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/ltcShock.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/marketModels.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/mortality.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Derives q(x) from the period life table registered at longevity/ssaPeriod2022.ts (ssa-table-4c6-period-life-table-vintage); the e(x)-to-q(x) derivation itself is engine math with no separate statutory claim, and this consumer is deliberately not pinned' }),
  'montecarlo/riskBasedGuardrails.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/rng.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/run.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/sharedPaths.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'montecarlo/survival.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'params/data/realYieldCurve2026.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'Treasury market-data snapshot; provenance in params/provenance.ts, not statute' }),
  'params/data/year2026.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'params/index.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The Trustees default haircut (2034, 17 percent) is registered under ssa-2026-trustees-oasdi-depletion-default-haircut, which pins the constant; the C-CPI-U-versus-plan-inflation indexing liberty is stated in the annually-indexed records naming indexFederalTaxPack' }),
  'params/provenance.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'params/state/data/year2026.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'params/state/index.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'params/state/types.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'types only; named by records for the shapes they define' }),
  'params/types.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'types only; named by records for the shapes they define' }),
  'projection/annualCashFlowCapture.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Form 8606 basis, QCD exclusion, annuity and penalty character composition; assembly composes results computed and registered elsewhere and enforces none of them, so no record names it' }),
  'projection/annualCashFlowIds.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualCashFlowReconciliation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualCashFlowShortfallAttribution.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualCashFlowYearSites.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualPassTransaction.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annualRetirementRuntimeJournal.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/annuityForms.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'projection/beneficiaryTraditionalIraAnnualPassConsumer.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/compare.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'after-tax estate haircuts incl. taxable step-up registered (irc-1014-a-1-basis-at-death-fair-market-value); Form 8606 basis exclusion, spousal rollover, HSA non-spouse income remain' }),
  'projection/employerRothCatchUp.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'projection/flatTax.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-30', note: 'deprecated alias that keeps the published projection/flatTax subpath resolving; the flat-rate test double it forwards to lives at testing/flatTax.ts and carries the IRC 86 claim' }),
  'projection/internal/fixedAssetDispositions.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-31', note: 'the fixed-asset disposition phase, moved out of simulatePlan; it orchestrates which property accounts sell and how a HECM on the sold home is repaid, and calls tax/propertySale.ts#propertySaleTax for the pricing — the §121 exclusion and depreciation-recapture claims stay registered against that file, which is where the arithmetic lives. Not a verbatim lift, and the difference is where a reader should look: what came across unchanged is the selection filter (type, planned sale year, cost basis present, value above zero), the propertySaleTax call and the values it is handed including the sale-year inflation growth, and the non-recourse payoff clamp and net-proceeds subtraction, operand for operand. What changed shape is HECM closure and the output. The inlined phase deleted from hecmStates inside its own loop; the helper takes a ReadonlyMap, records the ids it has closed in a set of its own so a second account sharing an id sees the closure the same way, and reports closesHecmForAccountId for the caller to delete on. The gain legs and the ledger payload are no longer accumulated and recorded in place either: they are returned per row, and the caller folds and publishes them in row order' }),
  'projection/internal/legacyAggregateDecisionCalculation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/internal/otherIncomeStreams.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-31', note: 'income pass 2 — the recurring and one-time income streams, the ones that are neither wages (pass 1) nor Social Security (pass 3) — moved out of simulatePlan. It decides which streams pay in a given year and how much, and labels each amount ordinary/capitalGain/none for the caller to route; it computes no tax itself and encodes no statutory rule, since the windows, the survivorship gate and the inflation election are all plan-model semantics. Not a verbatim lift, and the difference is where a reader should look. What came across unchanged is the two selection filters — the recurring start/end window, inclusive at both ends, with its anyAlive gate, and the one-time exact-year match — and the amount expressions operand for operand, including the two asymmetries the inlined phase carried and this one preserves rather than fixes: anyAlive gates recurring streams ONLY, so a one-time stream still pays in a post-death year, and a one-time amount is never inflation-adjusted while a recurring one may be. What changed shape is the output. The inlined phase accumulated into incomes.recurring, incomes.oneTime, ordinaryIncome and oneTimeGains and called recordRecurringIncome/recordOneTimeIncome in place, inside its own loop; the helper returns one discriminated row per contributing stream in plan.incomes order, recurring and one-time interleaved, never sums across them, and leaves every fold and both recorder calls to the caller. Two contract points a reader should not have to infer: rows are keyed by POSITION and never by stream id, because parsePlan accepts duplicate income-stream ids; and a zero-amount row is still returned, so the sink rather than the helper applies the non-positive drop' }),
  'projection/internal/tipsLadderAnnualCashFlow.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-30', note: 'the TIPS-ladder annual cash-flow phase, moved out of simulatePlan; carries the positive-inflation-adjustment OID claim and the deflation clamp registered at treas-reg-1-1275-7-d-4-positive-inflation-adjustment-oid and treas-reg-1-1275-7-f-1-deflation-adjustment-income. Not a verbatim lift either, on the same reading as the sibling row above: what came across unchanged is the per-ladder arithmetic, operand for operand — the offset-under-one gate and its purchase-year condition, the cash, prevInflFactor, accretion and taxable expressions, and the frozen-face lastAliveOffset branch. What changed shape is the output. The inlined phase accumulated into incomes.tipsLadder, ordinaryIncome, ladderTaxableInterest and ladderValueTotal and called recordTipsLadderCash in place, inside its own loop; the helper returns one discriminated row per ladder (none/preFlow/frozen/flow) and never sums across them, and the caller folds and publishes in row order' }),
  'projection/internal/types/aca.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/accountActivity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/cashFlow.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/market.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/optimizer.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/ownedIraReplay.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/result.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/retirementRuntime.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/tax.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; the one runtime value is the QSS-to-joint parameter mapping, and that file was swept rule-free on 2026-08-24' }),
  'projection/internal/types/yearLedger.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-29', note: 'one slice of the projection type surface, split verbatim out of projection/types.ts; declarations only, and that file was swept rule-free on 2026-08-24' }),
  'projection/moneyTolerance.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'half-cent funding fixed-point tolerance; numerical guard, not statute' }),
  'projection/optimizePlan.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'Flat 15% LTCG LP rate registered (irc-1-h-optimizer-flat-fifteen-percent-preferential-rate); other optimizer linearizations remain unregistered' }),
  'projection/optimizerAggregateConversionPromotion.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'same-owner trim registered under irc-408-d-3-A-i and the distributability predicate under irc-401-k-2-B-i; RMD-first ordering is an upstream snapshot contract enforced at resolveOwnerIraRmdSatisfaction, not here, and stays the residual' }),
  'projection/optimizerAggregateConversionPromotionRun.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/optimizerAllocatedCandidateComparison.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/optimizerExactLedgerComparison.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/ownedIraAnnualPhysicalTransactionInputs.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Form 8606 line-7/8 and QCD staging semantics; the input builder carries one combined distribution bucket, so it does not enforce the line-7-versus-8 split; no record' }),
  'projection/ownedNonRothIraAnnualObservation.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'April-15/weekend/Emancipation-Day filing deadline; no record' }),
  'projection/relocation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'projection/simulate.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-26', note: 'QCD/RMD/annuity/contribution/QLAC covered; residual 59½/HSA/Roth-five-year/Rule-of-55 proxies, inherited-Roth post-flip, Medicare age-65, HSA family-limit, spousal/survivor SS' }),
  'projection/types.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'rmd/applicableAge.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Named by treas-reg-1-401-a-9-5-d-1-ii-greater-of-employee-life-expectancy; the born-1959 record\'s contraryReading now records what the full IRB text of Announcement 2026-7 shows - it defers final regulations amending 1.401(a)(9)-4, -5, and -6 and never mentions paragraph (b)(2)(v) or the 1959 cohort, so no current guidance addresses the contest; residual: the RBD April-1 arm (this module consumes an asserted RBD-status fact) and the 70\u00bd/July-1949 cohort tiers pending a pre-SECURE historical-edition record' }),
  'rmd/jointLifeTable.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'rmd/rmd.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'rmd/rmdShortfallExcise.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'rules/coverageAttestations.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'registry/coverage tooling' }),
  'rules/coverageReport.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'registry/coverage tooling' }),
  'rules/describeRule.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'registry/coverage tooling' }),
  'rules/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'registry/coverage tooling' }),
  'rules/records/annuities.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/charitableDeductions.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/charitableDistributions.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/contributionAndDeferralLimits.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/earlyDistributionsAndSepp.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/healthSavingsAccounts.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/individualIncomeTax.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/investmentIncomeAndBasis.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/iraBasisAndRollovers.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/medicareAndHealthCoverage.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/requiredMinimumDistributions.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/rothAccounts.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/socialSecurity.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/statesMidwest.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/statesNortheast.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/statesSouthAtlantic.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/statesSouthCentral.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/statesWest.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/records/transfersAndUnmodeledRegimes.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'one slice of the record store, split out of taxRuleRegistry.ts; enforced by taxRuleRegistry.conformance.test.ts' }),
  'rules/symbolLines.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-28', note: 'registry/coverage tooling' }),
  'rules/taxRuleRegistry.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'the record store itself; enforced by taxRuleRegistry.conformance.test.ts' }),
  'scenarios/actionRows.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/comparison.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/contract.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/patch.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/scenarios.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/taxOpportunityView.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/taxStrategyEvaluation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/taxStrategyEvaluationRegistryCheck.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'scenarios/taxStrategyTradeoffs.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'schema/generate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'schema/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'schema/plan.v1.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'schema/plan.v2.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'schema/plan.v3.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'schema/plan.v4.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'schema/planSchemaMeta.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/benefitFactor.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/claimFactor.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Worker 62y0m-70y0m claim window registered under usc-42-402-worker-claim-window-62-to-70; DRC and early-reduction composition registered under cfr-20-404-313 and cfr-20-404-410 which now name the factor; spousal and ARF records already named it' }),
  'socialSecurity/disability.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-27', note: null }),
  'socialSecurity/familyMaximum.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/maritalBenefits.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Eligibility rules (10-yr divorce, 9-mo survivor marriage, age gates, remarriage forfeiture) have no records' }),
  'socialSecurity/nra.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-26', note: null }),
  'socialSecurity/piaFromEarnings.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'AIME pipeline (age 22–61 window, 5 lowest dropped, top-35 years, AWI indexing) not separately registered; the disability-freeze exclusion and post-entitlement recomputation base window ARE registered as approximations' }),
  'socialSecurity/ssaWageData.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/survivorBenefit.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'spending/abw.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'spending/flexibleGoals.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'spending/guardrails.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'spending/layers.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'spending/shapePresets.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'strategies/accountEligibility.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-25', note: 'SECURE 2020 gate portion of S2 treat-as-own election timing not registered to this file' }),
  'strategies/inheritedIra.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'strategies/iraBasis.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'strategies/optimizer.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'MILP prices brackets, IRMAA, ACA MAGI cap, RMD floors, §86 SS phase-in, LTCG; not registered here' }),
  'strategies/rothBasis.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'strategies/rothConversion.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Bracket/IRMAA/ACA FPL/senior-deduction sizing via computeFederalTax; no record names this file' }),
  'strategies/sepp.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'tax/aca.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'tax/aggregateBasisSale.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'tax/annualCharitableDeductionParameters.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: null }),
  'tax/federalTax.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-26', note: 'implements §86 SS inclusion, NIIT, AMT screen, senior-deduction phase-out, LTCG stacking with records naming it, but §170(b)(1)(I)(ii) category waterfall is applied only in the ledger file its record names' }),
  'tax/medicare.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-27', note: 'Part B/IRMAA premium path and Part B late-enrollment absence registered (usc-42-1395r-*, cfr-20-418-1205-1230-*); post-pack premiumScale (healthcare-inflation stand-in) remains' }),
  'tax/propertySale.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Section 121/1250 records name this file; the universal loss floor is registered as the approximated irc-165-c-personal-use-sale-loss-nondeductible - exact for personal-use property, overstating tax where an investment-property loss would deduct' }),
  'tax/stateTax.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'testing/flatTax.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-30', note: 'flat-rate test double injected only by test suites - the sole non-test importers are the deprecated projection/flatTax shim that republishes it on the published subpath and the pack-smoke script that verifies that subpath - so no RetireGolden code path injects it outside tests and the IRC 86 85 percent inclusion it applies never reaches a user-facing number; it is published, at testing/flatTax and through the deprecated projection/flatTax subpath, so an external consumer can call it directly; kept partial rather than rule-free so the claim stays visible if the file ever gains a production consumer' }),
  'testing/money.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'testing/planFixtures.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'version.generated.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: 'generated file' }),
  'version.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
})

/** Grandfather window closed with the 2026-08-24 baseline sweep; must stay empty. */
export const BASELINE_UNSWEPT: readonly string[] = Object.freeze([])

