/** Calculation catalog slice; independent worksheet claims, including disclosed discrepancies. */
import type { CalculationRecord } from '../calculationRegistry.js'

export const optimizerAndComparisonsRecords = {
  'conversion-coordinate-descent-search': {
    title: 'Conversion coordinate descent search',
    purpose: 'Refine an annual conversion schedule through deterministic local search.',
    kind: 'model',
    outputs: [],
    feeds: ['optimizer-recommended-conversion-annual', 'optimizer-schedule-conversion-total'],
    statement: 'decisions/search.ts#refineConversionSchedule deterministically searches annual Roth-conversion dollars by fixed-order coordinate descent, first coarse then fine steps, retaining only hard-constraint-feasible moves whose exact-ledger primary metric improves by more than the minimum, subject to simulation and sweep caps.',
    formula: {
      expression: 'for coarse then fine step, for each year coordinate try amount +/- step; retain a feasible candidate only when score > incumbent + minimumImprovement',
      variables: [
        { symbol: 'schedule', meaning: 'Annual conversion amounts', unit: 'nominal USD', domain: 'nonnegative' },
        { symbol: 'step', meaning: 'Coarse/fine move size', unit: 'USD', domain: 'positive' },
        { symbol: 'score', meaning: 'Objective metric', unit: 'objective dollars', domain: 'finite' },
      ],
      timing: 'deterministic annual-coordinate order under simulation and sweep budgets',
      rounding: 'schedule cents; no statistical tolerance',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/conversion-coordinate-descent-search.md',
    },
    limits: [
      'Local search only; no global-optimum claim. The worksheet score table is injected at the evaluation seam with a four-evaluation budget covering exactly its four entries; any unspecified probe fails closed. This proves search selection only. The returned aggregate schedule still passes downstream legal-owner/action readiness and publication gates, so it feeds rather than publishes optimizer recommendations.',
    ],
    implementedBy: ['packages/engine/src/decisions/search.ts'],
    implementedByFunctions: ['packages/engine/src/decisions/search.ts#refineConversionSchedule'],
    verifiedOn: '2026-09-17',
    provenance: { derivedBy: 'codex', implementedBy: 'codex', reviewedBy: 'cursor' },
  },
  'swr-rule-rate-and-initial-spend': {
    title: 'Swr rule rate and initial spend',
    purpose: 'Set initial spending from three published withdrawal-rate parameterizations.',
    kind: 'model',
    outputs: ['swr-rule-result-initial-rate-pct', 'swr-rule-result-initial-annual-spend'],
    feeds: [
      'swr-rule-result-depletion-year',
      'swr-rule-result-end-year',
      'swr-rule-result-ending-after-tax-estate',
      'swr-rule-result-lifetime-taxes-and-penalties',
    ],
    statement: 'decisions/swrComparator.ts#compareSwrRules assigns Bengen 4.7%, Morningstar 3.9%, or ERN 1.75%+0.5(100/CAPE) and multiplies that percent by starting investable dollars to set constant-real initial annual spending before a same-plan ledger comparison.',
    formula: {
      expression: 'rates = (4.7,3.9,1.75+0.5*(100/CAPE)); initialSpend = startingInvestable * rate/100',
      variables: [
        { symbol: 'CAPE', meaning: 'Cyclically adjusted price/earnings ratio', unit: '1', domain: 'positive' },
        { symbol: 'startingInvestable', meaning: 'Initial investable portfolio', unit: 'today USD', domain: 'nonnegative' },
      ],
      timing: 'initial constant-real annual spending, before ledger comparison',
      rounding: 'none',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/swr-rule-rate-and-initial-spend.md',
    },
    limits: [
      'Published rule parameterizations are planning lenses, not household safety guarantees. The worksheet pins rates and initial spending only; depletion, horizon, estate, and taxes come from the downstream ledger and are feeds.',
    ],
    implementedBy: ['packages/engine/src/decisions/swrComparator.ts'],
    implementedByFunctions: ['packages/engine/src/decisions/swrComparator.ts#compareSwrRules'],
    verifiedOn: '2026-09-17',
    provenance: { derivedBy: 'codex', implementedBy: 'codex', reviewedBy: 'cursor' },
  },
  'scenario-nullable-scalar-comparison': {
    title: 'Scenario nullable scalar comparison',
    purpose: 'Compare a nullable metric without turning absence into zero.',
    kind: 'composition',
    outputs: ['scenario-comparison-cell'],
    feeds: [],
    statement: 'scenarios/comparison.ts#nullableScalar preserves nullable baseline and proposal values and publishes proposal-baseline only when both exist, otherwise publishing a null delta, in the metric\'s own units and with no stated rounding.',
    formula: {
      expression: 'delta = proposal - baseline when baseline != null and proposal != null, else null',
      variables: [
        { symbol: 'baseline', meaning: 'Baseline metric value or absence', unit: 'the metric\'s own unit', domain: 'finite number or null' },
        { symbol: 'proposal', meaning: 'Proposal metric value or absence', unit: 'the metric\'s own unit', domain: 'finite number or null' },
      ],
      timing: 'one comparison cell',
      rounding: 'none stated',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/scenario-nullable-scalar-comparison.md',
    },
    limits: [
      'Comparability is conjunctive: absence is not numerical zero, so coercing a null operand to zero would present a comparison that does not exist. The pin is a non-exported helper, so the evidence asserts it through the exported compareScenarioPlans on a metric whose comparison cell is the nullable one (the headline depletion year).',
    ],
    implementedBy: ['packages/engine/src/scenarios/comparison.ts'],
    implementedByFunctions: [
      'packages/engine/src/scenarios/comparison.ts#nullableScalar',
      'packages/engine/src/scenarios/comparison.ts#compareScenarioPlans',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'scenario-scalar-comparison': {
    title: 'Scenario scalar comparison',
    purpose: 'Publish a scenario metric as baseline, proposal and a signed same-unit delta.',
    kind: 'composition',
    outputs: ['scenario-comparison-cell'],
    feeds: [],
    statement: 'scenarios/comparison.ts#scalar publishes a finite numeric metric\'s baseline, proposal and delta in that metric\'s own units, with delta = proposal - baseline and no stated rounding.',
    formula: {
      expression: 'delta = proposal - baseline',
      variables: [
        { symbol: 'baseline', meaning: 'Baseline metric value', unit: 'the metric\'s own unit', domain: 'finite' },
        { symbol: 'proposal', meaning: 'Proposal metric value', unit: 'the metric\'s own unit', domain: 'finite' },
      ],
      timing: 'one comparison cell',
      rounding: 'none stated',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/scenario-scalar-comparison.md',
    },
    limits: [
      'The signed identity is fixed: baseline and proposal are preserved rather than reordered by magnitude, and the delta stays in the metric\'s own unit rather than becoming a relative change. The pin is a non-exported helper, so the evidence asserts it through the exported compareScenarioPlans on a headline money metric.',
    ],
    implementedBy: ['packages/engine/src/scenarios/comparison.ts'],
    implementedByFunctions: [
      'packages/engine/src/scenarios/comparison.ts#scalar',
      'packages/engine/src/scenarios/comparison.ts#compareScenarioPlans',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'swr-rule-depletion-year': {
    title: 'Swr rule depletion year',
    purpose: 'Name the first rule-run year whose post-HECM shortfall clears the ledger tolerance.',
    kind: 'composition',
    outputs: ['swr-rule-result-depletion-year'],
    feeds: [],
    statement: 'decisions/swrComparator.ts#compareSwrRules publishes, for each constant-real rule run, the projection\'s first calendar year whose funding shortfall after any HECM backstop draw is strictly greater than ANNUAL_FUNDING_TOLERANCE_PLAN_DOLLARS, which is 0.005 nominal dollars, or null when no projection year crosses that gate.',
    formula: {
      expression: 'depletionYear = min { y : shortfallAfterHecm_y > 0.005 }, else null',
      variables: [
        { symbol: 'shortfallAfterHecm_y', meaning: 'Year y funding shortfall after any HECM backstop draw', unit: 'nominal USD', domain: 'nonnegative' },
        { symbol: 'tolerance', meaning: 'ANNUAL_FUNDING_TOLERANCE_PLAN_DOLLARS', unit: 'nominal USD', domain: '0.005' },
      ],
      timing: 'ordered rule-run ledger years',
      rounding: 'none; strict comparison against the residual budget',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/swr-rule-depletion-year.md',
    },
    limits: [
      'The comparison is strict, so a residual at or below half a cent is not depletion, and the explicit horizon keeps a shorter run from reading as depletion; the largest-shortfall year is not the answer either. The worksheet\'s third case, a sole shortfall of exactly 0.005 in one year, was not constructed from real inputs: the ledger funds to its own exact-cent fixed point, and no plan input reaches a residual of exactly half a cent in one year while leaving every other year funded, so the strictness of the comparison is evidenced by the claim and the first two cases only.',
    ],
    implementedBy: ['packages/engine/src/decisions/swrComparator.ts'],
    implementedByFunctions: ['packages/engine/src/decisions/swrComparator.ts#compareSwrRules'],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'swr-rule-end-year': {
    title: 'Swr rule end year',
    purpose: 'Publish the rule run\'s ledger endpoint rather than its depletion year.',
    kind: 'composition',
    outputs: ['swr-rule-result-end-year'],
    feeds: [],
    statement: 'decisions/swrComparator.ts#compareSwrRules publishes ProjectionResult.endYear, the final calendar year actually used by that safe-withdrawal-rule ledger run, without treating an earlier depletion year as the endpoint.',
    formula: {
      expression: 'SwrRuleResult.endYear = result.endYear',
      variables: [
        { symbol: 'result.endYear', meaning: 'Final calendar year of the rule run', unit: 'calendar year', domain: 'integer' },
        { symbol: 'result.depletionYear', meaning: 'Depletion year, present only as a discriminator', unit: 'calendar year or null', domain: 'integer or null' },
      ],
      timing: 'one completed rule run',
      rounding: 'none; integer calendar year',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/swr-rule-end-year.md',
    },
    limits: [
      'The simulation horizon is not depletion: substituting the depletion year, or recomputing a 30-year inclusive horizon from the start year, each name a different quantity. The worksheet\'s ledger endpoint and its depletion-year discriminator are supplied as a ProjectionResult literal at the simulate seam, so this proves the comparator\'s selection only; the ledger\'s own horizon arithmetic is out of scope for this record.',
    ],
    implementedBy: ['packages/engine/src/decisions/swrComparator.ts'],
    implementedByFunctions: ['packages/engine/src/decisions/swrComparator.ts#compareSwrRules'],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'swr-rule-ending-after-tax-estate': {
    title: 'Swr rule ending after tax estate',
    purpose: 'Republish the rule run\'s already composed after-tax estate.',
    kind: 'composition',
    outputs: ['swr-rule-result-ending-after-tax-estate'],
    feeds: [],
    statement: 'decisions/swrComparator.ts#compareSwrRules republishes the rule run\'s nominal ProjectionSummary.endingAfterTaxEstate as that rule\'s ending after-tax estate, without further discounting or recomputation.',
    formula: {
      expression: 'SwrRuleResult.endingAfterTaxEstate = summary.endingAfterTaxEstate',
      variables: [
        { symbol: 'summary.endingAfterTaxEstate', meaning: 'Rule-run after-tax estate from the upstream summary', unit: 'nominal USD', domain: 'finite' },
        { symbol: 'summary.endingEstateHeirTax', meaning: 'Heir-tax discount, present only as a discriminator', unit: 'nominal USD', domain: 'nonnegative' },
      ],
      timing: 'one completed rule run',
      rounding: 'none; copies the supplied summary value',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/swr-rule-ending-after-tax-estate.md',
    },
    limits: [
      'Estate tax discounting belongs to the upstream summary and must not be applied twice; publishing ending net worth instead is a different quantity. The worksheet\'s rule-run ledger is supplied as a ProjectionResult literal at the simulate seam, so the summary composition and the comparator\'s publication are both the real functions while the ledger run itself is not exercised here.',
    ],
    implementedBy: ['packages/engine/src/decisions/swrComparator.ts'],
    implementedByFunctions: ['packages/engine/src/decisions/swrComparator.ts#compareSwrRules'],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'swr-rule-lifetime-taxes-and-penalties': {
    title: 'Swr rule lifetime taxes and penalties',
    purpose: 'Republish the rule run\'s combined lifetime taxes and penalties.',
    kind: 'composition',
    outputs: ['swr-rule-result-lifetime-taxes-and-penalties'],
    feeds: [],
    statement: 'decisions/swrComparator.ts#compareSwrRules republishes the rule run\'s nominal ProjectionSummary.lifetimeTaxesAndPenalties as the taxes-and-penalties result for that constant-real spending rule, without another aggregation.',
    formula: {
      expression: 'SwrRuleResult.lifetimeTaxesAndPenalties = summary.lifetimeTaxesAndPenalties',
      variables: [
        { symbol: 'summary.lifetimeTaxesAndPenalties', meaning: 'Rule-run lifetime taxes and penalties from the upstream summary', unit: 'nominal USD', domain: 'finite' },
      ],
      timing: 'one completed rule run',
      rounding: 'none; copies the supplied summary value',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/swr-rule-lifetime-taxes-and-penalties.md',
    },
    limits: [
      'The upstream summary already sums all annual taxes and penalties, so publishing tax alone, or adding the separately displayed penalty amount to the already combined figure, changes the published quantity. The worksheet\'s annual tax and penalty rows are supplied as a ProjectionResult literal at the simulate seam; the summary aggregation and the comparator\'s publication are the real functions.',
    ],
    implementedBy: ['packages/engine/src/decisions/swrComparator.ts'],
    implementedByFunctions: ['packages/engine/src/decisions/swrComparator.ts#compareSwrRules'],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'exact-ledger-summary-comparison': {
    title: 'Exact ledger summary comparison',
    purpose: 'Publish the two exact-ledger estates and the ending-net-worth delta between them.',
    kind: 'formula',
    outputs: [
      'optimization-baseline-after-tax-estate',
      'optimization-candidate-after-tax-estate',
      'exact-ledger-validation-ending-net-worth-delta',
    ],
    feeds: [],
    statement: 'projection/optimizePlan.ts#evaluateExactLedgerSchedule publishes ExactLedgerValidation.baseline as summarizeProjection of the plan\'s shared baseline result and ExactLedgerValidation.candidate as summarizeProjection of the candidate schedule\'s own simulated result, and publishes endingNetWorthDelta as candidate.endingNetWorth minus baseline.endingNetWorth.',
    formula: {
      expression: 'baseline = summarizeProjection(sharedBaselineResult); candidate = summarizeProjection(candidateResult); endingNetWorthDelta = candidate.endingNetWorth - baseline.endingNetWorth',
      variables: [
        { symbol: 'baseline.endingAfterTaxEstate', meaning: 'Shared baseline result summary ending after-tax estate', unit: 'nominal USD at horizon', domain: 'finite' },
        { symbol: 'candidate.endingAfterTaxEstate', meaning: 'Candidate schedule result summary ending after-tax estate', unit: 'nominal USD at horizon', domain: 'finite' },
        { symbol: 'baseline.endingNetWorth', meaning: 'Shared baseline result summary ending net worth', unit: 'nominal USD at horizon', domain: 'finite' },
        { symbol: 'candidate.endingNetWorth', meaning: 'Candidate schedule result summary ending net worth', unit: 'nominal USD at horizon', domain: 'finite' },
      ],
      timing: 'one candidate schedule validated against the plan\'s shared baseline run',
      rounding: 'none; the summarized dollar figures carry binary floating-point representation',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/exact-ledger-summary-comparison.md',
    },
    limits: [
      'No value from one result may be paired with the other result\'s label: the baseline estate is the shared baseline run\'s summary and the candidate estate is the candidate schedule\'s own run, and the delta is on ending net worth rather than on after-tax estate. Beyond the worksheet\'s four summary figures the fixture assumes a validated plan whose only estate-discounted holding is one non-inherited traditional account at a 25 percent flat heir rate, so each result\'s final-year balance for that account is what turns its ending net worth into the worksheet\'s after-tax estate; both projections are supplied as ProjectionResult values at the exported validation entry, so the summary composition and the validation wrapper are the real functions while neither ledger run is exercised here. The entry also requires a requested schedule, which the worksheet does not name and the fixture leaves empty. recommendationState has no census family this round and is not published by this record.',
    ],
    implementedBy: [
      'packages/engine/src/projection/optimizePlan.ts',
      'packages/engine/src/decisions/evaluateCandidate.ts',
    ],
    implementedByFunctions: [
      'packages/engine/src/projection/optimizePlan.ts#evaluateExactLedgerSchedule',
      'packages/engine/src/projection/optimizePlan.ts#evaluateExactLedgerScheduleCalculation',
      'packages/engine/src/decisions/evaluateCandidate.ts#evaluateCandidate',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'exact-ledger-conversion-execution': {
    title: 'Exact ledger conversion execution',
    purpose: 'Report how much of a requested conversion schedule the exact ledger actually executed.',
    kind: 'formula',
    outputs: [
      'exact-ledger-validation-requested-conversion-total',
      'exact-ledger-validation-executed-conversion-ratio',
      'exact-ledger-validation-first-materially-unexecuted-year',
    ],
    feeds: [],
    statement: 'projection/optimizePlan.ts#evaluateExactLedgerSchedule sums the requested schedule into requestedConversionTotal, sums the candidate result\'s YearResult.rothConversion into the executed total, publishes executedConversionRatio as min(1, executed / requested) and exactly 1 when nothing was requested, and publishes firstMateriallyUnexecutedYear as the first ascending requested year whose shortfall is more than max(DECISION_MATERIAL_SHORTFALL_DOLLARS, requested times DECISION_MATERIAL_SHORTFALL_PCT), else null.',
    formula: {
      expression: 'requested = sum(schedule.amount); executed = sum(candidate.years.rothConversion); ratio = requested > 0 ? min(1, executed / requested) : 1; firstMateriallyUnexecutedYear = min { y ascending : requested_y - executed_y > max(1000, requested_y * 0.05) }, else null',
      variables: [
        { symbol: 'requested_y', meaning: 'Requested conversion dollars in year y', unit: 'nominal USD', domain: 'nonnegative' },
        { symbol: 'executed_y', meaning: 'Candidate result rothConversion in year y', unit: 'nominal USD', domain: 'nonnegative' },
        { symbol: 'DECISION_MATERIAL_SHORTFALL_DOLLARS', meaning: 'Absolute material shortfall margin', unit: 'nominal USD', domain: '1000' },
        { symbol: 'DECISION_MATERIAL_SHORTFALL_PCT', meaning: 'Proportional material shortfall margin', unit: '1', domain: '0.05' },
      ],
      timing: 'one candidate schedule against its own exact-ledger run, requested years tested in ascending order',
      rounding: 'none; the dollar sums carry binary floating-point representation and the materiality comparison is strict',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/exact-ledger-conversion-execution.md',
    },
    limits: [
      'The materiality margin is resolved per year from that year\'s own requested amount, not once from the schedule total, and the comparison is strictly more than, so a shortfall equal to its margin does not qualify; the ratio is capped at 1 so an over-execution cannot read as more than the whole request, and the zero-request branch is the stated exact 1 rather than a division. Beyond the worksheet\'s rows the fixture assumes a validated plan with one non-inherited traditional account and a baseline result that the entry requires and the worksheet does not name; both projections are supplied as ProjectionResult values at the exported validation entry, so the requested-versus-executed arithmetic is the real function while neither ledger run is exercised here. ExactLedgerValidation.executedConversionTotal has no census family this round, so it is read only as the ratio\'s numerator and is not published by this record.',
    ],
    implementedBy: [
      'packages/engine/src/projection/optimizePlan.ts',
      'packages/engine/src/decisions/evaluateCandidate.ts',
    ],
    implementedByFunctions: [
      'packages/engine/src/projection/optimizePlan.ts#evaluateExactLedgerSchedule',
      'packages/engine/src/decisions/evaluateCandidate.ts#buildConversionExecution',
      'packages/engine/src/decisions/evaluateCandidate.ts#evaluateCandidate',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'exact-ledger-traditional-depletion': {
    title: 'Exact ledger traditional depletion',
    purpose: 'Name the first year the plan\'s own traditional balances are exhausted under a candidate schedule.',
    kind: 'formula',
    outputs: ['exact-ledger-validation-traditional-depletion-year'],
    feeds: [],
    statement: 'projection/optimizePlan.ts#evaluateExactLedgerSchedule publishes ExactLedgerValidation.traditionalDepletionYear through decisions/evaluateCandidate.ts#findTraditionalDepletionYear as the first ascending candidate-result year whose non-inherited traditional account balances sum to at most the validation tolerance, one dollar by default, and null when no year does.',
    formula: {
      expression: 'traditionalDepletionYear = min { y ascending : sum over own traditional accounts a of balance(a, y) <= toleranceDollars }, else null',
      variables: [
        { symbol: 'balance(a, y)', meaning: 'Year-end balance of own traditional account a in year y', unit: 'nominal USD', domain: 'nonnegative' },
        { symbol: 'toleranceDollars', meaning: 'Validation tolerance, DECISION_NEUTRAL_TOLERANCE_DOLLARS by default', unit: 'nominal USD', domain: '1' },
      ],
      timing: 'candidate-result years in ascending order; the first qualifying year wins',
      rounding: 'none; the boundary is inclusive at the tolerance',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/exact-ledger-traditional-depletion.md',
    },
    limits: [
      'Inherited traditional balances are excluded, the boundary is inclusive so an owned sum of exactly the tolerance qualifies, and a later fully drained year cannot displace the first qualifying one. Beyond the worksheet\'s three account balance columns the fixture assumes a validated plan whose two owned traditional accounts and one inherited traditional account carry the worksheet\'s ids, an empty requested schedule, and a baseline result that the entry requires and the worksheet does not name; the candidate projection is supplied as a ProjectionResult value at the exported validation entry, so the selection is the real function while no ledger run is exercised here.',
    ],
    implementedBy: [
      'packages/engine/src/projection/optimizePlan.ts',
      'packages/engine/src/decisions/evaluateCandidate.ts',
    ],
    implementedByFunctions: [
      'packages/engine/src/projection/optimizePlan.ts#evaluateExactLedgerSchedule',
      'packages/engine/src/decisions/evaluateCandidate.ts#findTraditionalDepletionYear',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'simple-candidate-evaluation-comparison': {
    title: 'Simple candidate evaluation comparison',
    purpose: 'Compare one simple conversion candidate with the shared baseline on the exact ledger.',
    kind: 'formula',
    outputs: [
      'simple-candidate-evaluation-after-tax-estate-delta',
      'simple-candidate-evaluation-executed-conversion-total',
      'simple-candidate-evaluation-incomplete-computation-years',
      'simple-candidate-evaluation-lifetime-tax-delta',
      'simple-candidate-evaluation-money-lasts-years-delta',
    ],
    feeds: [],
    statement: 'projection/optimizePlan.ts#evaluateSimpleConversionCandidates publishes each SimpleCandidateEvaluation as the sum of the candidate result\'s YearResult.rothConversion, the candidate-minus-baseline differences of summarizeProjection\'s endingAfterTaxEstate and lifetimeTaxesAndPenalties, the candidate-minus-baseline difference of lastsThrough (a result\'s depletionYear, or its endYear + 1 when it never depletes), and the ascending sorted union across both results of the years whose taxComputation.status or hecmComputation.status is incomplete.',
    formula: {
      expression: 'executedConversionTotal = sum(candidate.years.rothConversion); afterTaxEstateDelta = candidate.endingAfterTaxEstate - baseline.endingAfterTaxEstate; lifetimeTaxDelta = candidate.lifetimeTaxesAndPenalties - baseline.lifetimeTaxesAndPenalties; moneyLastsYearsDelta = lastsThrough(candidate) - lastsThrough(baseline); incompleteComputationYears = sorted union of the incomplete years of both results',
      variables: [
        { symbol: 'lastsThrough(result)', meaning: 'Result depletionYear, or endYear + 1 when it never depletes', unit: 'calendar year', domain: 'integer' },
        { symbol: 'candidate.endingAfterTaxEstate', meaning: 'Candidate result summary ending after-tax estate', unit: 'nominal USD at horizon', domain: 'finite' },
        { symbol: 'candidate.lifetimeTaxesAndPenalties', meaning: 'Candidate result summary lifetime taxes and penalties', unit: 'nominal USD over projection', domain: 'finite' },
        { symbol: 'incomplete(result)', meaning: 'Years whose taxComputation.status or hecmComputation.status is incomplete', unit: 'calendar years', domain: 'set of integers' },
      ],
      timing: 'one simple conversion candidate against the plan\'s shared baseline run',
      rounding: 'none; the dollar sum and the dollar differences carry binary floating-point representation',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/simple-candidate-evaluation-comparison.md',
    },
    limits: [
      'Every difference is candidate minus baseline, the conversion sum is the candidate result\'s rows alone, a non-depleting result lasts through endYear + 1 rather than endYear, and the incomplete years are a de-duplicated ascending union across both results rather than a concatenation. Beyond the worksheet\'s inputs the smallest exported entry that publishes these fields generates its own fixed set of fill-to-target candidates and runs each one through the ledger, so the fixture supplies the candidate result at the simulate seam and the baseline result directly; it also assumes a validated plan whose only estate-discounted holding is one non-inherited traditional account at a 20 percent flat heir rate, so each result\'s final-year balance for that account is what turns its ending net worth into the worksheet\'s after-tax estate. In the no-incomplete-status branch the optional incompleteComputationYears key is omitted, not set to an empty list, as the worksheet states since its 2026-09-18 revision (the first derivation expected an empty list, which the fixture found); the fixture asserts the omission and the empty union it stands for. recommendationState has no census family this round and is not published by this record.',
    ],
    implementedBy: [
      'packages/engine/src/projection/optimizePlan.ts',
      'packages/engine/src/decisions/evaluateCandidate.ts',
    ],
    implementedByFunctions: [
      'packages/engine/src/projection/optimizePlan.ts#evaluateSimpleConversionCandidates',
      'packages/engine/src/projection/optimizePlan.ts#buildRichCandidates',
      'packages/engine/src/projection/optimizePlan.ts#incompleteComputationYears',
      'packages/engine/src/decisions/evaluateCandidate.ts#evaluateCandidate',
      'packages/engine/src/decisions/evaluateCandidate.ts#lastsThroughYear',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'exact-ledger-tournament-margin': {
    title: 'Exact ledger tournament margin',
    purpose: 'Report how far the tournament winner beat the solver schedule it displaced, and zero when it displaced none.',
    kind: 'model',
    outputs: ['exact-ledger-tournament-margin-over-milp-dollars'],
    feeds: [],
    statement: 'projection/optimizePlan.ts#runExactLedgerTournament publishes ExactLedgerTournament.marginOverMilpDollars as the winning candidate\'s exact after-tax estate delta minus the displaced recommendable MILP schedule\'s exact after-tax estate delta, and as exactly 0 whenever no MILP comparison was made, which includes the MILP-winner branch and both the incumbent and none fallbacks; a candidate replaces a recommendable MILP only when its delta is more than that schedule\'s delta plus DEFAULT_TOURNAMENT_SWITCH_MARGIN_DOLLARS, which is 1000 dollars.',
    formula: {
      expression: 'marginOverMilpDollars = milpRecommended ? winnerEstateDelta - milpDelta : 0; the candidate replaces the MILP only when winnerEstateDelta > milpDelta + 1000',
      variables: [
        { symbol: 'winnerEstateDelta', meaning: 'Winning candidate\'s exact after-tax estate delta over the shared baseline', unit: 'nominal USD at horizon', domain: 'finite' },
        { symbol: 'milpDelta', meaning: 'Recommendable post-processed MILP schedule\'s exact after-tax estate delta, 0 when none is recommendable', unit: 'nominal USD at horizon', domain: 'finite' },
        { symbol: 'switchMarginDollars', meaning: 'DEFAULT_TOURNAMENT_SWITCH_MARGIN_DOLLARS', unit: 'nominal USD', domain: '1000' },
      ],
      timing: 'one tournament over the plan\'s simple candidates and its post-processed MILP schedule',
      rounding: 'none; the dollar figures carry binary floating-point representation and the switch comparison is strict',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/exact-ledger-tournament-margin.md',
    },
    limits: [
      'The zero convention is the evidenced branch: with no MILP result supplied the published margin is 0 on both the none and the incumbent outcome, so a candidate-versus-incumbent difference must never be reported there, and a no-traditional plan reports source none with an empty schedule rather than an incumbent request. The worksheet\'s third case — a candidate that beats a recommendable MILP by more than the 1000-dollar switch margin, and the strictness of that threshold at exactly 1000 — is a solver-run limit and was NOT constructed: the worksheet supplies no estate inputs for the MILP schedule, and the entry takes a post-processed solver schedule rather than a dollar figure, so no assertion here can pin that branch or its published difference. Beyond the worksheet\'s two inputs the fixture assumes, for the none case, a validated single-person plan with one cash account, zero returns, zero inflation, zero state tax and zero base spending, and for the incumbent case a validated single-person retiree plan with an 800000-dollar traditional account beside a taxable and a cash account, 4 percent returns, a 25 percent heir rate, 45000 dollars of base spending and a planning age of 85, both run with the production federal tax calculator from start year 2026 so Y1 is 2026; on the incumbent plan the tournament\'s own candidate winner is withheld by the retirement-action readiness veto, which is what routes the run to the incumbent fallback the worksheet describes. Both runs exercise the real ledger; nothing is supplied at a seam.',
    ],
    implementedBy: ['packages/engine/src/projection/optimizePlan.ts'],
    implementedByFunctions: [
      'packages/engine/src/projection/optimizePlan.ts#runExactLedgerTournament',
      'packages/engine/src/projection/optimizePlan.ts#fallbackTournament',
      'packages/engine/src/projection/optimizePlan.ts#incumbentExecutedConversions',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'exact-ledger-cleaned-schedule': {
    title: 'Exact ledger cleaned schedule',
    purpose: 'Trim a raw solver conversion schedule to what the exact ledger actually executes.',
    kind: 'model',
    outputs: ['optimizer-recommended-conversion-annual'],
    feeds: ['exact-ledger-tournament-margin-over-milp-dollars'],
    statement: 'projection/optimizePlan.ts#postProcessExactLedgerSchedule publishes ExactLedgerPostProcessing.cleanedSchedule as the per-year minimum of the raw requested conversion and the ledger\'s executed conversion, taking that minimum only when execution exceeds the neutral tolerance and zero otherwise, and records each materially changed year as an ExactLedgerScheduleAdjustment whose reason is ledger-capped when the cleaned amount survives, dropped-zero when it does not, and estate-pruned when the trailing prune pass removes the year; rounding is declared on that reason union and never assigned (decision D-ADJUSTMENT-ROUNDING-REASON).',
    formula: {
      expression: 'cleaned_y = executed_y > neutralTolerance ? min(requested_y, executed_y) : 0; reason_y = cleaned_y <= neutralTolerance ? dropped-zero : ledger-capped, or estate-pruned when the prune pass drops year y',
      variables: [
        { symbol: 'requested_y', meaning: 'Raw solver schedule amount for year y', unit: 'nominal USD', domain: 'nonnegative' },
        { symbol: 'executed_y', meaning: 'max(0, the rerun ledger\'s rothConversion for year y)', unit: 'nominal USD', domain: 'nonnegative' },
        { symbol: 'neutralTolerance', meaning: 'DECISION_NEUTRAL_TOLERANCE_DOLLARS', unit: 'nominal USD', domain: '1' },
      ],
      timing: 'raw request, exact-ledger execution, rerun, repeated to a fixed point within the stabilization budget',
      rounding: 'adjustment rows carry cents-rounded requested, executed and cleaned amounts; the dollar totals carry binary floating-point representation',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/exact-ledger-cleaned-schedule.md',
    },
    limits: [
      'Cleaned is the per-year minimum, not the request: keeping the request republishes 15000 dollars in a year the ledger funded with 5000, and summing the raw requests publishes 30000 dollars rather than the cleaned 20000. The reason on that year is ledger-capped, never the declared-but-never-assigned rounding. Of the worksheet\'s three live reasons only ledger-capped is realized by its stated inputs; dropped-zero and estate-pruned were NOT constructed from them, because each needs a different raw schedule and, for estate-pruned, a plan whose trailing conversion year harms the exact estate — neither of which the worksheet states, so the fixture asserts instead that the run\'s reasons lie inside the three live values and that rounding is not among them. Beyond the worksheet\'s inputs the fixture assumes a validated single-person plan with a 10000-dollar cash account and an empty Roth account beside the 20000-dollar traditional one, zero healthcare expenses, a planning age of 67 and the production federal tax calculator from start year 2026, so Y1 is 2026 and Y2 is 2027; the raw schedule is a full OptimizedSchedule literal whose per-year solver rows are zero apart from the conversion, which the entry requires and the worksheet does not name. The MILP-sourced winning schedule the worksheet mentions is a solver-run limit with no number and is not asserted here.',
    ],
    implementedBy: ['packages/engine/src/projection/optimizePlan.ts'],
    implementedByFunctions: [
      'packages/engine/src/projection/optimizePlan.ts#postProcessExactLedgerSchedule',
      'packages/engine/src/projection/optimizePlan.ts#buildCleanedConversionsFromExecution',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
  'claim-age-co-optimization': {
    title: 'Claim age co-optimization',
    purpose: 'Count the Social Security claim combinations priced and publish the current-claim and joint exact estates.',
    kind: 'model',
    outputs: [
      'claim-age-co-optimization-combinations-evaluated',
      'claim-age-co-optimization-current-claim-exact-estate',
      'claim-age-co-optimization-joint-exact-estate',
    ],
    feeds: ['optimizer-recommended-conversion-annual'],
    statement: 'projection/optimizePlan.ts#optimizePlanCoOptimizingClaimAge publishes ClaimAgeCoOptimization.combinationsEvaluated as one plus the claim candidates decisions/generators.ts#socialSecurityClaimGenerator produced (up to two Social Security streams times the three canonical claim ages 62y0m, the person’s own full retirement age computed from the birth year and labelled FRA, and 70y0m, skipping each stream\'s own current claim age), currentClaimExactEstate as the exact after-tax estate of the optimum at the current claim ages, and jointExactEstate as the exact after-tax estate of the best evaluated claim-and-schedule pair, which stays the current-claim estate unless a candidate beats it by more than DEFAULT_CLAIM_SWITCH_MARGIN_DOLLARS, which is 1000 dollars.',
    formula: {
      expression: 'combinationsEvaluated = 1 + generatedClaimCandidates; jointExactEstate = the best pair estate that clears currentClaimExactEstate + 1000, else currentClaimExactEstate; winningClaimLabel and winningClaimPatch are null exactly when no pair clears it',
      variables: [
        { symbol: 'generatedClaimCandidates', meaning: 'Claim candidates from socialSecurityClaimGenerator: streams (at most 2) times the canonical ages that differ from that stream\'s current claim', unit: 'count', domain: 'integer 0 to 6' },
        { symbol: 'currentClaimExactEstate', meaning: 'Exact after-tax estate of the optimum at the plan\'s current claim ages', unit: 'nominal USD at horizon', domain: 'finite' },
        { symbol: 'jointExactEstate', meaning: 'Exact after-tax estate of the winning claim-and-schedule pair', unit: 'nominal USD at horizon', domain: 'finite' },
        { symbol: 'claimSwitchMarginDollars', meaning: 'DEFAULT_CLAIM_SWITCH_MARGIN_DOLLARS', unit: 'nominal USD', domain: '1000' },
      ],
      timing: 'one full conversion optimum per claim combination, the current claim included',
      rounding: 'none; the count is an integer and the estates carry binary floating-point representation',
    },
    justification: {
      kind: 'derivation',
      worksheet: 'DOCS/calculations/optimizer-and-comparisons/claim-age-co-optimization.md',
    },
    limits: [
      'The count includes the current claim and excludes the stream\'s own current age as a candidate: a stream already claiming at 70y0m generates two candidates and so evaluates three combinations, and a plan with no stream still evaluates one. The middle point is the person’s own full retirement age from socialSecurity/nra.ts#fraForBirthYear, 66y2m for the example’s 1956-01-01 birth (effective birth year 1955). The two estates are RUN-PINNED, not derived: the worksheet states no dollar figure for either, so the fixture\'s example carries the value one execution of the co-optimizer produced on the stated plan, and it is evidence of that execution rather than of an independent derivation. What is derived is their equality: with no traditional balance every schedule is empty and no claim clears the 1000-dollar margin, so the joint estate IS the current-claim estate and both claim outputs are null. The strictness of that margin at exactly 1000 dollars was NOT constructed: it needs a candidate whose exact estate sits one margin above the current-claim optimum, which no plan input the worksheet states can produce. Beyond the worksheet\'s inputs the fixture assumes validated single-person plans with one cash account and no traditional balance, zero returns, zero inflation, zero state tax, zero base spending, a birth date that makes the person 70 in the start year, an integer planning age of 70 (the plan schema admits no 70y1m) and the production federal tax calculator from start year 2026; the count is asserted at the generator itself, whose context takes the plan\'s own baseline ledger run.',
    ],
    implementedBy: [
      'packages/engine/src/projection/optimizePlan.ts',
      'packages/engine/src/decisions/generators.ts',
    ],
    implementedByFunctions: [
      'packages/engine/src/projection/optimizePlan.ts#optimizePlanCoOptimizingClaimAge',
      'packages/engine/src/projection/optimizePlan.ts#winnerExactEstate',
      'packages/engine/src/decisions/generators.ts#socialSecurityClaimGenerator',
    ],
    verifiedOn: '2026-09-18',
    provenance: { derivedBy: 'codex', implementedBy: 'claude', reviewedBy: 'cursor' },
  },
} satisfies Record<string, CalculationRecord>
