/**
 * TEST ONLY: the Learning Center's editorial review metadata, keyed by slug.
 *
 * Who an article is written for (`audience`), how often it is re-reviewed
 * (`reviewCadence`), and whether it leans on current-year dollar figures or
 * rules (`currentYearSensitive`). No page renders any of it, so it lives here
 * instead of in learn/articleIndex.ts, which rides the landing critical path
 * and ships only what the link, card, search and category surfaces read.
 *
 * learn/articleEditorial.test.ts fails when an index slug has no entry here,
 * when an entry names no index slug, or when an index entry carries one of
 * these fields again; learn/learn.test.tsx holds current-year-sensitive
 * articles to their sources and review cadence. Add an entry with every new
 * article (DOCS/standards.md, Adding a Learning Center article). testSupport/
 * is not published, and no production module imports this file.
 */

import type { ArticleEditorial } from '../learn/learningRegistry'

/** One entry per article, in ARTICLE_INDEX order. */
export const ARTICLE_EDITORIAL: Readonly<Record<string, ArticleEditorial>> = {
  'about-retiregolden': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'how-to-read-a-retirement-projection': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'todays-dollars-vs-future-dollars': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'what-retiregolden-models': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'how-retiregolden-checks-its-math': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'reading-the-results-page': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'where-the-money-comes-from-and-goes': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'understanding-monte-carlo-success-rate': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'roth-conversion-basics': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'filling-a-tax-bracket-with-roth-conversions': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'how-the-optimizer-values-after-tax-estate': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'marginal-vs-effective-tax-rate': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'why-roth-conversions-raise-other-costs': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'social-security-claiming-age-basics': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'pia-aime-and-bend-points': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'break-even-useful-lens': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'spousal-and-survivor-benefits': { audience: 'beginner', reviewCadence: 'rule-change', currentYearSensitive: false },
  'ssdi-and-retirement-planning': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'social-security-taxes-vs-benefits': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'earnings-test-before-fra': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'cola-and-inflation-protection': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'divorced-spousal-and-survivor-records': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'dynamic-spending-guardrails': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'risk-based-guardrails': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'tips-ladders': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'social-security-bridge': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'funded-ratio': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'building-a-retirement-spending-budget': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'spending-profiles-and-the-retirement-smile': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'survivor-spending-in-couple-plans': { audience: 'beginner', reviewCadence: 'rule-change', currentYearSensitive: false },
  'how-much-can-i-spend': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'trust-fund-haircut-scenarios': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'mortality-weighted-social-security': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'irmaa-two-year-lookback': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'appealing-irmaa-ssa-44': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'aca-premium-tax-credits-and-magi': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'agi-magi-and-taxable-income': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'healthcare-before-65': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'healthcare-after-65': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'what-retirement-healthcare-really-costs': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'hsas-and-qualified-medical-expenses': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'long-term-care-costs-and-insurance': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'medicare-part-b-vs-part-d-irmaa': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'withdrawal-order-basics': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'rmds-required-minimum-distributions': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'qcds-qualified-charitable-distributions': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'widows-penalty-and-survivor-brackets': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'paying-conversion-taxes-taxable-vs-ira': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'rule-of-55-and-72t': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'inherited-ira-10-year-rule': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'account-types-overview': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'traditional-vs-roth-contributions': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'employer-match-and-contribution-order': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'hsas-as-retirement-accounts': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'taxable-brokerage-basis-and-capital-gains': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'pensions-and-annuities': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'real-estate-home-equity-and-debt': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'rsus-and-espp': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'fees-expense-ratios-and-compounding-drag': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'long-term-care-insurance-as-risk-transfer': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'permanent-life-insurance-in-a-plan': { audience: 'intermediate', reviewCadence: 'rule-change', currentYearSensitive: false },
  'insurance-in-your-retirement-plan': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'survivor-planning-for-couples': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'after-tax-estate': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'step-up-in-basis': { audience: 'intermediate', reviewCadence: 'rule-change', currentYearSensitive: true },
  'beneficiaries-and-account-titling': { audience: 'beginner', reviewCadence: 'rule-change', currentYearSensitive: true },
  'sequence-of-returns-risk': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'what-monte-carlo-proves': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'historical-vs-random-return-models': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'inflation-risk': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'longevity-risk': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'three-big-questions-spending-time-risk': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'how-assumptions-change-the-answer': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'planning-for-couples-and-survivor-years': { audience: 'beginner', reviewCadence: 'rule-change', currentYearSensitive: false },
  'why-small-tax-cliffs-can-matter': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'planner-overview': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'using-scenarios-to-compare-choices': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'reading-the-social-security-analysis-page': { audience: 'beginner', reviewCadence: 'rule-change', currentYearSensitive: false },
  'using-assumptions-and-provenance': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'reports-csv-exports-and-sharing': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'privacy-what-stays-in-your-browser': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'moving-to-retiregolden': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'seed-your-plan-from-your-tax-return': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'troubleshooting-surprising-results': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'how-the-optimizer-thinks': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'ordinary-income-vs-capital-gains': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'standard-deduction-senior-deduction-and-itemizing': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'how-social-security-is-taxed': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'niit-high-income-investment-tax': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'state-income-taxes-in-retirement': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'what-changes-when-you-move-states': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'tax-cliffs-and-bracket-edges': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'tax-loss-and-gain-harvesting': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'why-95-percent-is-not-a-guarantee': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'sensitivity-testing-what-changes-the-answer': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'what-is-fire': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'savings-rate-biggest-lever': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'fi-number-and-four-percent-rule': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'how-to-model-accumulation': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'understanding-your-plan-assumptions': { audience: 'beginner', reviewCadence: 'annual', currentYearSensitive: true },
  'assumption-general-inflation': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'assumption-healthcare-inflation': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'assumption-investment-returns': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'assumption-social-security-cola': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'assumption-social-security-trust-fund': { audience: 'intermediate', reviewCadence: 'rule-change', currentYearSensitive: true },
  'assumption-longevity-planning-age': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'assumption-state-tax-override': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'assumption-recent-magi': { audience: 'intermediate', reviewCadence: 'annual', currentYearSensitive: true },
  'assumption-heir-tax-rate': { audience: 'intermediate', reviewCadence: 'stable', currentYearSensitive: false },
  'example-couple': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-under-saved-single': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-bracket-fill-roth': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-early-retiree-aca': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-rmd-irmaa': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-inherited-ira-beneficiary': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-survivor-years': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-moving-state-tax': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-ltc-shock': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-early-career-match': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-aggressive-saver': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-coast-fire': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-barista-fire': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-bridge-early-retirement': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-lean-fat-fire': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-hsa-stealth-retirement': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-salary-growth-escalation': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-guardrails-flex-goals': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-annuity-purchases-estate': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-glidepath-allocation': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-hsa-property-depth': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-fixed-target-spending': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-no-annuity-brokerage': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-static-allocation-control': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-brokerage-no-hsa': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-all-401k-no-bridge': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-brokerage-bridge-401k': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-no-head-start-grad': { audience: 'beginner', reviewCadence: 'stable', currentYearSensitive: false },
  'example-trump-account-head-start': { audience: 'beginner', reviewCadence: 'rule-change', currentYearSensitive: true },
}
