import type { LearningArticle } from '../learningRegistry'

export const assumptionRecentMagiArticle: LearningArticle = {
  slug: 'assumption-recent-magi',
  title: 'Recent MAGI and the IRMAA lookback',
  description: 'Why RetireGolden asks for your recent Modified Adjusted Gross Income, and how it affects your early retirement Medicare costs.',
  category: 'assumptions',
  tags: ['taxes', 'magi', 'irmaa', 'medicare', 'lookback'],
  audience: 'intermediate',
  status: 'ready',
  lastReviewed: '2026-06-30',
  reviewCadence: 'annual',
  sourceUrls: [
    'https://www.cms.gov/newsroom/fact-sheets/2026-medicare-parts-b-premiums-deductibles',
  ],
  relatedArticles: [
    'irmaa-two-year-lookback',
    'medicare-part-b-vs-part-d-irmaa',
    'understanding-your-plan-assumptions',
  ],
  relatedPlannerRoutes: ['/plan/:planId/assumptions'],
  currentYearSensitive: true,
  priority: 'P1',
  blocks: [
    {
      type: 'prose',
      md: "Medicare premiums for high earners are adjusted upward based on income. These surcharges are called the **Income-Related Monthly Adjustment Amount (IRMAA)**. Because the government determines IRMAA using tax returns from **two years prior**, your plan needs a seed value to model your Medicare costs in the first few years of retirement.",
    },
    { type: 'heading', text: 'Quick takeaways' },
    {
      type: 'list',
      items: [
        'RetireGolden defaults **Recent annual MAGI** to **$0**, meaning no high-income surcharges are modeled for your first two years of Medicare unless you override it.',
        'Medicare uses a **two-year lookback**: your 2026 premiums are based on the Modified Adjusted Gross Income (MAGI) reported on your 2024 tax return.',
        'Entering your pre-retirement MAGI here ensures that the initial years of your Medicare projections are accurate, capturing any lag between high employment earnings and retirement.',
      ],
    },
    { type: 'heading', text: 'Why is there a lookback?' },
    {
      type: 'prose',
      md: "When you enroll in Medicare at age 65 (or continue coverage), the Social Security Administration retrieves your tax data from the IRS. Because of processing lag, the most recent finalized tax return is from two years ago. For example:",
    },
    {
      type: 'list',
      items: [
        '**2026 Medicare premiums** look back to your **2024 tax return**.',
        '**2027 Medicare premiums** look back to your **2025 tax return**.',
      ],
    },
    {
      type: 'table',
      caption: 'How the seed rolls off.',
      columns: ['Projection year', 'MAGI source RetireGolden uses', 'What it affects'],
      rows: [
        ['First Medicare year', 'Recent annual MAGI seed', 'Initial IRMAA tier and Medicare premium estimate'],
        ['Second Medicare year', 'Prior-year plan MAGI or the recent seed where applicable', 'The remaining lookback transition'],
        ['Later years', 'MAGI generated by the projection itself', 'Ongoing IRMAA and tax-driven healthcare costs'],
      ],
    },
    {
      type: 'prose',
      md: "This two-year lag means that if you retire at 65 and transition from a high salary to a low retirement income, your Medicare premiums for the first two years will still reflect your high working years. RetireGolden uses the **Recent annual MAGI** field as the input for this two-year-prior income to model the correct premiums for those initial years.",
    },
    { type: 'heading', text: 'Life-changing events (Form SSA-44)' },
    {
      type: 'prose',
      md: "If your income drops significantly due to a qualifying \"life-changing event\" (such as retirement, marriage, or loss of income), you can file Form SSA-44 with the Social Security Administration to request a premium reduction. RetireGolden does not automatically model this appeal, but you can simulate it by entering a lower MAGI value in this field if you plan to appeal.",
    },
    { type: 'heading', text: 'Watch-outs' },
    {
      type: 'list',
      items: [
        'Recent MAGI is an input seed, not an ongoing income forecast.',
        'If you expect a successful SSA-44 appeal, model the lower recent MAGI you expect Medicare to use.',
      ],
    },
    { type: 'heading', text: 'Where this shows up in the app' },
    {
      type: 'prose',
      md: 'You can enter your pre-retirement income under **Recent annual MAGI** on the **Assumptions** screen. This value is used solely as a starting seed for the lookback calculation and does not affect the engine\'s ongoing income projections.',
    },
  ],
}
