/**
 * Coverage attestations for `actions/`.
 *
 * One slice of the coverage attestation registry. `../coverageAttestations.ts`
 * composes every slice into `COVERAGE_ATTESTATIONS`; read it for what an
 * attestation means and how sweeps work. Entries were moved here verbatim from
 * the single file this registry used to be.
 */
import type { CoverageAttestation } from '../coverageAttestations.js'

export const actionsAttestations: Readonly<Record<string, CoverageAttestation>> = Object.freeze({
  'actions/actionResult.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-03', note: null }),
  'actions/aggregateRothConversionOwnerAllocation.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'same-owner pro-rata allocation long registered under irc-408-d-3-A-i; the RMD-before-conversion ordering it relies on is enforced upstream (resolveOwnerIraRmdSatisfaction), and this file consumes the post-RMD snapshot as a contract rather than enforcing it - that contract stays the residual' }),
  'actions/annualHsaOpeningAuthority.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaPenaltyEvaluation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaPhysicalMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaReimbursementLedger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaTreatmentBindingCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualHsaWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualIraBasisAllocation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualLiabilityRunIdentity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualOwnedNonRothIraPoolCapacity.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'QCD pool restricted to donor-owned non-Roth IRAs; no record' }),
  'actions/annualQcdActionExecutionEvidence.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/annualQcdDeductionTreatmentCoordinator.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/annualQcdDerivedTaxCharacter.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Owned-source eligibility arrives as typed AcceptedQcdSourceEligibilityEvidence - this module consumes what the QCD execution prerequisite evaluator enforces, and the 408(d)(8) source records are registered at that evaluator; the taxable/excludable/basis partition is registered under the composition-order and taxable-first records' }),
  'actions/annualQcdExecution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdExecutionPrerequisite.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdItemizedLiabilityReconciliation.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdItemizedSection170Ledger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdPhysicalExecution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The account gate enforces owned-and-not-inherited IRA sourcing and the beneficiary and Roth 408(d)(8) source records name the stager; the ongoing SEP/SIMPLE exclusion is enforced and registered at the execution prerequisite evaluator' }),
  'actions/annualQcdResidualForm8606.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The residual pass keeps line-7 and line-8 pools distinct (registered under form-8606-lines-7-and-8-distinct-distribution-staging, which now names the stager) and consumes allocation evidence computed under the registered 408(d)(2) fraction' }),
  'actions/annualQcdStandardSection170pLedger.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdTaxCharacterPostPass.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/annualQcdUnifiedTransactionFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualRetirementActionMovementCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/annualRetirementActionPublication.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-27', note: null }),
  'actions/annualRetirementPhysicalEventInventory.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Inherited-RMD regime; owner-RMD start age; spouse-as-own transition; annuity/Form 8606 treatment; direct-trustee QCD origin; no record' }),
  'actions/annualSection68ItemizedDeduction.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiarySpousalElectionStatus.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualPhysicalTransaction.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualPlanApplication.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Beneficiary-owned inherited traditional-IRA/death-year source gate; no record' }),
  'actions/beneficiaryTraditionalIraAnnualRuntimeCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraAnnualSimulatorDelta.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/beneficiaryTraditionalIraDeathPenalty.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/beneficiaryTraditionalIraMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdActionIdentity.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-24', note: 'Residual-RMD source restricted to beneficiary-owned inherited traditional IRA; no record' }),
  'actions/beneficiaryTraditionalIraResidualRmdAllocation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdAnnualRefinalization.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The line-7 rebuild with a forced-zero line 8 is registered under the lines-7-and-8 staging split and the inherited-rollover bar (a beneficiary pool can never carry conversions), both of which now name the refinalization' }),
  'actions/beneficiaryTraditionalIraResidualRmdChronology.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdMovementCandidate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraResidualRmdPhysicalTransaction.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/beneficiaryTraditionalIraWithdrawalCharacter.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'The nonzero-line-8 refusal mixes two things the reviewers rightly split: for a non-spouse beneficiary it is the 408(d)(3)(C)(i) bar, registered at that record\'s own enforcers, and for a spouse beneficiary a conversion after electing ownership is lawful but unsupported - the refusal reason names exactly that, so the engine-scope half stays the residual here' }),
  'actions/civilDate.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/contract.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-25', note: null }),
  'actions/conversionLinkedWithdrawalGroup.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/conversionLinkedWithdrawalGroupExecution.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/conversionTaxFundingEvidence.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/exactCentProRata.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/execution.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'equity-compensation execution character registered as irc-83-a-equity-compensation-execution-character (approximated), which names this file; the 2026-08-25 note predated that record by a day' }),
  'actions/freeze.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-03', note: null }),
  'actions/identity.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/index.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/money.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualCandidateCoordinator.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualCandidateTransaction.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The wrapper runs its own owned non-inherited gate (account.inherited must be undefined) and the pool-scope record now pins it; line semantics are registered where they are enforced, at the movement stager' }),
  'actions/ownedNonRothIraAnnualFilingEvidence.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Prior-year contribution window covered and the ownedIraPool filter is now pinned by the pool-scope record; the January-1 opening-basis anchor stays an engine convention (408(d)(2)(C) computes values as of the close of the year) and is the sole residual' }),
  'actions/ownedNonRothIraAnnualFilingSourceResolver.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'The resolver computes the owned non-inherited pool itself (its account filter) and the pool-scope record now pins it; its remaining issues are binding and dedup integrity' }),
  'actions/ownedNonRothIraAnnualFinalization.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraAnnualPhysicalTransaction.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Same-owner Roth destination and designated-Roth vehicle refusal registered under irc-408-d-3-A-i and irc-408A-d-3-B, and line-7/line-8 categorization under form-8606-lines-7-and-8-distinct-distribution-staging; QCD charitable-debit scope remains unregistered' }),
  'actions/ownedNonRothIraAnnualPlanCoordinator.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'The owner-wide non-inherited pool filter and the out-of-pool line-8 refusal are registered under irc-408-d-2-A-owner-wide-non-inherited-ira-pool; the line-7/line-8 stacking composition and the exact age-59\u00bd threshold representation remain the residuals' }),
  'actions/ownedNonRothIraAnnualPostCandidateEvidence.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Pool completeness (every owned non-inherited sibling, employer/inherited/foreign refused) is registered under irc-408-d-2-A-owner-wide-non-inherited-ira-pool and the contribution window was already covered; the line 1/4/6/9 staging composition and the path\'s type-level explicit-zero line 8 remain the residuals' }),
  'actions/ownedNonRothIraMovementCandidate.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Line-7 staging registered under form-8606-line-7-owned-ira-movement-staging; the owned traditional/SEP/SIMPLE source gate is registered under irc-408-d-2-A-owner-wide-non-inherited-ira-pool, which pins the stager\'s source-evidence refusal' }),
  'actions/ownedNonRothIraPenaltyCoverageEvidenceId.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-03', note: null }),
  'actions/ownedNonRothIraPenaltyPrerequisite.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Age, 10%/25% rates, disability, SEPP, SIMPLE period and scope covered; the death exception is rejected through owner-alive evidence and irc-72-t-2-A-ii now names the evaluator' }),
  'actions/ownedNonRothIraSeppAnnualReconciliation.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraSeppCurrentPaymentCandidate.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/ownedNonRothIraWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/plainData.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-03', note: null }),
  'actions/planBalanceAdapter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: 'named by the sub-cent discharge record; planDollarsMoveNoLedgerCent defines when that rule applies' }),
  'actions/qcdDeductibleContributionOffset.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/reasons.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/retirementActionCandidateIdentityAllocator.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'conversion source and destination identity registered under irc-408-d-3-A-i, the inherited-source refusal under irc-408-d-3-C-i, and the named-action designated-Roth refusal under irc-408A-d-3-B (conversionDestinationIssue kind gate); QCD source-IRA restrictions remain open' }),
  'actions/retirementActionManualReview.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'replacement source-owner and Roth-destination identity checks registered under irc-408-d-3-A-i; the type gate here does not discriminate a designated Roth (that vehicle refusal lives in the identity allocator), and the QCD source-owner clause remains open' }),
  'actions/rothConversionExecution.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'ordering and inherited-bar records name executeRothConversions; the positive-basis deferred-character branch publishes null character for the downstream annual 408(d)(2) pass to resolve, and that deferral plus the direct-vehicle gates remain the residual' }),
  'actions/structuralId.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-08-24', note: null }),
  'actions/taxableWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'actions/traditionalEmployerPlanPenaltyPrerequisite.ts': Object.freeze({ status: 'partial', sweptOn: '2026-08-29', note: 'Rule of 55, employer-SEPP, permitted methods, public-safety, recapture and the age-59½ threshold are registered records naming this file, and irc-72-t-2-A-iii now names the disability arm; the 10% rate application site for employer plans remains the residual' }),
  'actions/traditionalEmployerPlanWithdrawalCharacter.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
})
