/**
 * Coverage attestations for `socialSecurity/`.
 *
 * One slice of the coverage attestation registry. `../coverageAttestations.ts`
 * composes every slice into `COVERAGE_ATTESTATIONS`; read it for what an
 * attestation means and how sweeps work. Entries were moved here verbatim from
 * the single file this registry used to be.
 */
import type { CoverageAttestation } from '../coverageAttestations.js'

export const socialSecurityAttestations: Readonly<Record<string, CoverageAttestation>> = Object.freeze({
  'socialSecurity/analysis/breakEven.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-29', note: "the break-even chart: cumulative own benefits at whole-year claim ages, each year priced by the ledger's year function (socialSecurity/householdYear.ts) for the own benefit alone with the person's wages, and each pair's crossing (social-security-claim-break-even); it adds no statute of its own" }),
  'socialSecurity/analysis/claimants.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-28', note: "the Social Security claimants the analysis prices: each person's first stream, the PIA the one resolver gives, whether the ledger's disability schedule replaces the claim age, and the ranking's whole-year claim ages; it calls the registered resolver and disability schedule and adds no statute of its own" }),
  'socialSecurity/analysis/credits.ts': Object.freeze({ status: 'partial', sweptOn: '2026-09-27', note: "the covered-work credit estimate (covered-work-credit-estimate). Residual: the quarter-of-coverage counting of 42 U.S.C. 413(a)(2)(A) and 20 CFR 404.143(a), the annual amount from 1978 and $50 a quarter before, has no rule record; the calculation record states and cites it" }),
  'socialSecurity/analysis/expectedValue.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-29', note: "the benefits-only expected value (social-security-expected-value): survival weights and discounting over the paths householdPaths.ts prices with the ledger's year function; it adds no statute of its own" }),
  'socialSecurity/analysis/householdPaths.ts': Object.freeze({ status: 'registered', sweptOn: '2026-09-29', note: "the paths the benefits-only models weight (both spouses alive, and each survivor after each death year), each year priced by the ledger's year function (socialSecurity/householdYear.ts) with the plan's wage rows and exempt amounts; named by usc-42-403-f-3-retirement-earnings-test, usc-42-403-f-5-earnings-counted and social-security-expected-value" }),
  'socialSecurity/analysis/oasdiReturn.ts': Object.freeze({ status: 'registered', sweptOn: '2026-09-27', note: "OASDI tax paid in today's dollars and the benefits-to-contributions ratio; named by oasdi-paid-in-today-dollars, benefits-to-contributions-ratio and irc-3101-a-oasdi-employee-tax-rate" }),
  'socialSecurity/analysis/survivorSwitching.ts': Object.freeze({ status: 'registered', sweptOn: '2026-09-29', note: "survivor and own benefit switching for a widow(er) living alone (survivor-switching-expected-value); it applies the registered survivor-benefit and claim-factor rules, the marital gates and the registered earnings-test year (socialSecurity/earningsTest.ts); its own earnings-test stream (strategyStreamWithEarningsTest) is named by cfr-20-404-412-b-arf-effective-fra-month, for the widow(er) adjustment at 62, and usc-42-403-f-1-earnings-test-month-charging, for charging a benefit only from its first month of entitlement" }),
  'socialSecurity/colaFactor.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-27', note: "the ledger's Social Security COLA factor and trust-fund haircut, plan assumptions (social-security-cola-factor); no statute" }),
  'socialSecurity/cpiU.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-27', note: "BLS CPI-U annual averages 1937 to 2025 (cpi-u-annual-average); a published price series, no statute" }),
  'socialSecurity/oasdiTaxRates.ts': Object.freeze({ status: 'registered', sweptOn: '2026-09-27', note: "SSA's effective OASDI tax rates by year, 1937 to 2026; named by oasdi-tax-rate-history and irc-3101-a-oasdi-employee-tax-rate" }),
  'socialSecurity/annualTiming.ts': Object.freeze({ status: 'rule-free', sweptOn: '2026-09-01', note: 'shared parser for the already-schema-validated ISO birth date used by annual Social Security projection and milestone consumers. It performs no age, entitlement, or benefit arithmetic; the rule-bearing payable-month boundary remains registered in projection/internal/annualSocialSecurity.ts' }),
  'socialSecurity/benefitFactor.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/claimFactor.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-29', note: 'Worker 62y0m-70y0m claim window registered under usc-42-402-worker-claim-window-62-to-70; DRC and early-reduction composition registered under cfr-20-404-313 and cfr-20-404-410 which now name the factor; spousal and ARF records already named it' }),
  'socialSecurity/dualEntitlement.ts': Object.freeze({ status: 'registered', sweptOn: '2026-09-27', note: 'own benefit plus the separately reduced spouse excess, the first month of the spouse benefit, and the spouse factor at that month, for a current and a divorced spouse; named by usc-42-402-q-3-B-k-3-A-current-spouse-dual-entitlement and the dual-entitlement-composition calculation' }),
  'socialSecurity/earningsTest.ts': Object.freeze({ status: 'registered', sweptOn: '2026-09-29', note: "the retirement earnings test's year: the excess earnings and their month-by-month charging, the worker's first against the family benefit on his record, with each crediting month; shared by the ledger's year function and the analysis models; named by usc-42-403-f-3-retirement-earnings-test, usc-42-403-f-1-earnings-test-month-charging, usc-42-403-b-1-worker-excess-charged-to-family, usc-42-403-f-3-fra-year-months-before-fra and poms-rs-00615-482-arf-crediting-months" }),
  'socialSecurity/householdYear.ts': Object.freeze({ status: 'partial', sweptOn: '2026-09-29', note: "one year of a household's Social Security, month by month where a month can differ, then the earnings test: the one year function the projection and the analysis models share; named by social-security-benefit-annual and the earnings-test, crediting, FRA-month, deceased-crediting, divorced-after-widowhood and widow(er)-reduction records; current-spouse dual entitlement delegates to the registered dualEntitlement helpers, the widow(er) entitlement month to survivorBenefit#widowEntitlementAgeMonths (for a former spouse, maritalBenefits#formerSpouseSurvivorEntitlementAgeMonths) and the widow(er) limit to survivorBenefitMonthly. Residual, as it was on annualSocialSecurity.ts: person and stream selection, candidate ordering, COLA, haircut and publication are ledger conventions with no rule record" }),
  'socialSecurity/disability.ts': Object.freeze({ status: 'registered', sweptOn: '2026-09-12', note: 'cash-benefit TWP/EPE/SGA helpers retained; Medicare continuation boundary assertSsdiMedicareContinuationNotDeterminedFromCashBenefitFacts (usc-42-426-b-disability-trial-work-medicare-continuation)' }),
  'socialSecurity/familyMaximum.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/maritalBenefits.ts': Object.freeze({ status: 'partial', sweptOn: '2026-09-29', note: 'Living-divorced, ordinary-widow, surviving-divorced duration, and surviving-divorced remarriage eligibility gates, plus half-PIA and survivor pricing, are named on this file; the first month of a former spouse\'s survivor benefit freed by the end of a remarriage before 60 (formerSpouseSurvivorEntitlementAgeMonths) is named by usc-42-402-q-6-A-iii-widow-reduction-from-entitlement-month; the divorced-spouse amount delegates to the registered dualEntitlement.ts composition. Residual: claimant-has-claimed timing (claimantAge vs claimAge) is an engine convention with no record; survivor amount assembly is delegated to already-registered survivorBenefit.ts/claimFactor.ts/nra.ts without a borrowed pin here' }),
  'socialSecurity/nra.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-26', note: null }),
  'socialSecurity/openClaims.ts': Object.freeze({ status: 'partial', sweptOn: '2026-09-28', note: "the whole-year claim-age grid, registered under usc-42-402-worker-claim-window-62-to-70 (gridClaimAges). Residual: the already-claimed test (a claim whose year is before the plan's start year is fixed: 42 U.S.C. 402(a), 20 CFR 404.621(a)(3), withdrawal under 404.640(b)(4) and suspension under 402(z) not modeled) has no rule record; the social-security-claim-age-sweep calculation record states and cites it" }),
  'socialSecurity/piaFromEarnings.ts': Object.freeze({ status: 'partial', sweptOn: '2026-09-27', note: 'Initial-computation base window and annual indexed-earnings penny rounding registered as approximations on records/socialSecurityEarnings.ts; the computation-year count with the 1951 floor, the contribution and benefit base cap and the cost-of-living increases since eligibility are settled there. Residuals: future unpublished AWI/bend points use awiForYearOrLatest / bendPointsForEligibilityYearOrLatest; disability young-worker dropout, disability-year eligibility/indexing, prior-entitlement termination gaps, childcare dropout, and alternative widow indexing remain unmodeled. Disability freeze and post-entitlement recomputation stay on the socialSecurity shard.' }),
  'socialSecurity/ssaWageData.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
  'socialSecurity/survivorBenefit.ts': Object.freeze({ status: 'registered', sweptOn: '2026-08-24', note: null }),
})
