/**
 * The annual ledger's own shapes: per-person year state and the income,
 * expense, and withdrawal aggregates a projection year publishes.
 *
 * One slice of the projection type surface. `../../types.ts` re-exports every
 * slice, so `projection/types.js` stays the single public specifier for all of
 * them; the package export map blocks `projection/internal/*`, so this module
 * is not separately importable. Declarations and the commentary attached to
 * them were moved here verbatim, so a block that says "above" or "below" may
 * now point across a module boundary.
 */
export interface PersonYearState {
  personId: string
  /** Age attained during this calendar year (year − birth year). */
  ageAttained: number
  /**
   * Alive while `ageAttained` ≤ this run's effective life age for the person
   * (`SimulateOptions.deathAgeByPersonId` when set, else plan
   * `longevity.planningAge`). Detectors that classify death timing must read
   * these flags (and year-to-year alive transitions) — never re-derive death
   * year from plan planningAge alone, which drifts under longevity overrides.
   */
  alive: boolean
  /**
   * Last full year of life used for this run's `alive` flag (deathAge override
   * or planningAge). Optional on partial fixtures; `simulatePlan` always
   * publishes it so detectors can place the first deceased year without
   * re-reading plan longevity.
   */
  lifeAge?: number
}

export interface YearIncomes {
  wages: number
  /**
   * Σ over living people of that person's benefit. Own retirement (or SSDI)
   * rows add pia × claim-age factor × payable months (0 before the claim year,
   * 12 − claim months in it, 12 after) × the COLA factor × the haircut factor;
   * a divorced-spouse marital, current-spouse spousal (the lower earner's own
   * monthly + max(0, 0.5 × the higher PIA × the spousal factor − own monthly),
   * the excess capped by the family maximum) or survivor step-up candidate
   * replaces the running amount only when larger;
   * then, while under FRA, the earnings test withholds max(0, (wages − the
   * below-FRA limit) / 2), or ÷ 3 against the FRA-year limit in that year,
   * capped at the benefit. COLA factor: the inflation factor from the start
   * year under matchInflation, else (1 + annualPct / 100)^(year − start year);
   * haircut factor: 1 − cutPct / 100 from ssHaircut.fromYear, else 1.
   */
  socialSecurity: number
  pension: number
  annuity: number
  /**
   * TIPS-ladder cash flows, summed over ladders: (coupons + maturing
   * principal) × the ladder's funding scale × the cumulative inflation factor
   * from the start year, at offset = year − anchor year ≥ 1 while someone is
   * alive, where coupons = Σ face × couponRatePct / 100 over rungs with
   * maturityOffset ≥ offset and maturing principal is the face of the rungs
   * maturing at that offset; 0 in the purchase year, with no one alive, or
   * without ladders.
   */
  tipsLadder: number
  recurring: number
  oneTime: number
  taxableInterest: number
  ordinaryDividends: number
  qualifiedDividends: number
  taxableYield: number
  /** Federally tax-exempt interest generated by taxable accounts this year. Cash-real but never ordinary income; characterized per DOCS §20. */
  taxExemptInterest: number
  /**
   * Cash income for the year: `wages + socialSecurity + pension + annuity +
   * tipsLadder + recurring + oneTime + taxableYield + taxExemptInterest`.
   * taxableInterest, ordinaryDividends and qualifiedDividends characterize
   * taxableYield for tax purposes and do not join the sum again.
   */
  total: number
}

export interface YearExpenses {
  /**
   * Recurring lifestyle spending actually intended this year, after any
   * guardrail cut: `requiredLifestyle + targetLifestyle × min(1, guardrailFactor)
   * + idealLifestyleFunded + excessLifestyleFunded` (the full target layer when
   * no guardrail policy is active). With a policy active the two funded
   * upside layers draw on `max(0, discretionaryMultiplier − 1) ×
   * guardrailStepBasis` (ideal first, then excess), where guardrailStepBasis
   * is max(targetLifestyle, ideal + excess lifestyle, 1); so both are 0 in
   * any year the multiplier is at or below 1, every cutting year included.
   * Without a policy the budget is the full ideal plus excess lifestyle.
   * One-time goals and the system-computed costs are not in it; `total`
   * adds them.
   */
  baseSpending: number
  /** One-time goals funded this year, in nominal dollars. */
  oneTimeGoals: number
  /** Debt principal & interest (incl. any scheduled lump-sum payoff this year). */
  debtService: number
  /** Property tax + homeowner's insurance on owned properties (continues after mortgage payoff). */
  propertyCosts: number
  /**
   * Pre-65 marketplace premiums net of ACA credit + Medicare (Part B incl.
   * IRMAA, Part D surcharge, extras). Per living person the year splits at the
   * Medicare birth month into marketplace months and Medicare months: Medicare
   * months add the annual premium (with IRMAA) × months / 12 plus the extras
   * × months × the health inflation factor; marketplace months with the credit
   * off add the pre-65 monthly premium × months × the health inflation factor,
   * and with the credit on enter the gross enrollment premium instead. The
   * ACA fixed point then publishes healthcare excluding enrollment + the
   * economic net premium when it converges, else + the gross premium. The two
   * month counts partition the year (Medicare months = 12 − marketplace
   * months); the tier premium with IRMAA is inflated from the pack year, while
   * the extras and the marketplace premium use the health inflation factor
   * from the start year.
   */
  healthcare: number
  /** Level (fixed-nominal) insurance premiums charged this year (LTC + permanent life). */
  insurancePremiums: number
  /** Gross LTC care-episode cost this year (additive spending spike, before any policy offset). */
  careCost: number
  /** LTC policy benefit applied against careCost this year (income-tax-free; reduces net spending). */
  ltcBenefit: number
  /**
   * Must-fund spending this year: system-computed costs (healthcare, debt,
   * property, insurance, net LTC) + the required-floor lifestyle layer +
   * required-classified funded goals, plus the nominal amount of any
   * required-classified goal the flexible-goal scheduler skipped this year
   * (intended spending that never happened). A guardrail policy never cuts
   * below this.
   */
  requiredSpending: number
  /**
   * Full intended spending with no guardrail cut: the required base (the
   * system-computed costs, the required lifestyle layer and required-classified
   * funded goals, before any skipped amount) + the full target lifestyle layer
   * + target-classified funded goals, plus the nominal amounts of the
   * target-classified and required-classified goals the scheduler skipped this
   * year, each counted once. Equals `total` for older fixed-target plans
   * without ideal/excess layers.
   */
  targetSpending: number
  /** Incremental ideal spending intended this year above the target lifestyle. */
  idealSpending: number
  /** Incremental excess/opportunistic spending intended this year above ideal. */
  excessSpending: number
  /** Full intended spending with no guardrail cut across required/target/ideal/excess. */
  intendedSpending: number
  /** Discretionary multiplier the guardrail policy applied this year (1 = no cut). */
  guardrailFactor: number
  /**
   * Net outflow for the year: `baseSpending + oneTimeGoals + debtService +
   * propertyCosts + healthcare + insurancePremiums + careCost − ltcBenefit`.
   * The layer summaries (required, target, ideal, excess, intended) describe
   * how baseSpending was built and are not additional members; a later
   * healthcare adjustment moves healthcare and this total together.
   */
  total: number
}

/** Withdrawal totals by account category (sequential order: cash → taxable → traditional → roth → hsa). */
export interface YearWithdrawals {
  cash: number
  taxable: number
  traditional: number
  roth: number
  hsa: number
  /**
   * `cash + taxable + traditional + roth + hsa`, with one known departure.
   * The publishing site composes this total as the need-based category total
   * + RMDs + SEPP payments + inherited forced distributions + retirement-action
   * proceeds, and composes the categories separately: cash and taxable add
   * the retirement-action cash, equity-compensation and taxable proceeds;
   * traditional adds RMDs, SEPP payments and inherited ordinary income; roth
   * adds the forced inherited Roth distributions. A non-qualified inherited
   * Roth distribution's taxable earnings therefore enter traditional as well
   * as roth, and the categories exceed this total by that slice
   * (D-INHERITED-ROTH-SLICE). The three retirement-action class amounts are
   * composed from tax-character and coverage evidence while the proceeds are
   * the executed dispositions; their agreement is not asserted here.
   */
  total: number
}
