/**
 * The annual ledger's own shapes: per-person year state and the income,
 * expense, and withdrawal aggregates a projection year publishes.
 *
 * One slice of the projection type surface. `../../types.ts` re-exports every
 * slice, so `projection/types.js` stays the single public specifier for all of
 * them; the package export map blocks `projection/internal/*`, so this module
 * is not separately importable. Declarations and the commentary attached to
 * them were moved here verbatim, so a block that says "above" or "below" may
 * now point across a module boundary.
 */
export interface PersonYearState {
  personId: string
  /** Age attained during this calendar year (year − birth year). */
  ageAttained: number
  /**
   * Alive while `ageAttained` ≤ this run's effective life age for the person
   * (`SimulateOptions.deathAgeByPersonId` when set, else plan
   * `longevity.planningAge`). Detectors that classify death timing must read
   * these flags (and year-to-year alive transitions) — never re-derive death
   * year from plan planningAge alone, which drifts under longevity overrides.
   */
  alive: boolean
  /**
   * Last full year of life used for this run's `alive` flag (deathAge override
   * or planningAge). Optional on partial fixtures; `simulatePlan` always
   * publishes it so detectors can place the first deceased year without
   * re-reading plan longevity.
   */
  lifeAge?: number
}

export interface YearIncomes {
  wages: number
  socialSecurity: number
  pension: number
  annuity: number
  /** TIPS-ladder cash flows (coupons + maturing principal); 0 when the plan has no ladders. */
  tipsLadder: number
  recurring: number
  oneTime: number
  taxableInterest: number
  ordinaryDividends: number
  qualifiedDividends: number
  taxableYield: number
  /** Federally tax-exempt interest generated by taxable accounts this year. Cash-real but never ordinary income; characterized per DOCS §20. */
  taxExemptInterest: number
  total: number
}

export interface YearExpenses {
  baseSpending: number
  oneTimeGoals: number
  /** Debt principal & interest (incl. any scheduled lump-sum payoff this year). */
  debtService: number
  /** Property tax + homeowner's insurance on owned properties (continues after mortgage payoff). */
  propertyCosts: number
  /** Pre-65 marketplace premiums net of ACA credit + Medicare (Part B incl. IRMAA, Part D surcharge, extras). */
  healthcare: number
  /** Level (fixed-nominal) insurance premiums charged this year (LTC + permanent life). */
  insurancePremiums: number
  /** Gross LTC care-episode cost this year (additive spending spike, before any policy offset). */
  careCost: number
  /** LTC policy benefit applied against careCost this year (income-tax-free; reduces net spending). */
  ltcBenefit: number
  /**
   * Must-fund spending this year: system-computed costs (healthcare, debt,
   * property, insurance, net LTC) + the required-floor lifestyle layer +
   * required-classified funded goals. A guardrail policy never cuts below this.
   */
  requiredSpending: number
  /**
   * Full intended spending with no guardrail cut: requiredSpending + the full
   * target lifestyle layer + target-classified goals. Equals `total` for older
   * fixed-target plans without ideal/excess layers.
   */
  targetSpending: number
  /** Incremental ideal spending intended this year above the target lifestyle. */
  idealSpending: number
  /** Incremental excess/opportunistic spending intended this year above ideal. */
  excessSpending: number
  /** Full intended spending with no guardrail cut across required/target/ideal/excess. */
  intendedSpending: number
  /** Discretionary multiplier the guardrail policy applied this year (1 = no cut). */
  guardrailFactor: number
  total: number
}

/** Withdrawal totals by account category (sequential order: cash → taxable → traditional → roth → hsa). */
export interface YearWithdrawals {
  cash: number
  taxable: number
  traditional: number
  roth: number
  hsa: number
  total: number
}
